site_name: DALi UI Reference
site_url: https://dalihub.github.io/dali-ui/
use_directory_urls: false
site_description: High-performance C++ UI documentation.
repo_name: dalihub/dali-ui
repo_url: https://github.com/dalihub/dali-ui
docs_dir: build/doc/source

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - mkdoxy:
      projects:
        daliUi:
          src-dirs: >-
            dali-ui-foundation/public-api
            dali-ui-foundation/integration-api
            dali-ui-components/public-api
            dali-ui-components/integration-api
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.h *.md"
            EXTRACT_ANON_NSPACES: "NO"
            RECURSIVE: "YES"
            EXCLUDE_PATTERNS: "*/internal/*"
            EXTRACT_ALL: "YES"
            EXTRACT_PRIVATE: "NO"
            EXTRACT_STATIC: "YES"
            HIDE_UNDOC_MEMBERS: "NO"
            SOURCE_BROWSER: "YES"
            STRIP_FROM_INC_PATH: "."
            INCLUDE_PATH: "dali-ui-foundation dali-ui-components"
            ENABLE_PREPROCESSING: "YES"
            MACRO_EXPANSION: "YES"
            SEARCH_INCLUDES: "YES"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Home: index.md
  - API Reference:
      - 'Class List': 'daliUi/annotated.md'
      - 'Class Index': 'daliUi/classes.md'
      - 'Namespace List': 'daliUi/namespaces.md'
      - 'Files': 'daliUi/files.md'
