// Generated by dali-ui preprocessor. Do not modify.
#ifndef DALI_UI_CHAIN_INPUTFIELD_METHODS

#define DALI_UI_CHAIN_INPUTFIELD_METHODS(ChildClass) \
  DALI_UI_CHAIN_VIEW_METHODS(ChildClass) \
  /** \
  * @brief Sets the text. \
  * \
  * @param[in] text The text to display in UTF-8 format. \
  */ \
  ChildClass& SetText(const Dali::String& text) { InputField::SetText(text); return *this; } \
  /** \
  * @brief Sets the font family of the text. \
  * \
  * @param[in] fontFamily The requested font family to use. \
  */ \
  ChildClass& SetFontFamily(const Dali::String& fontFamily) { InputField::SetFontFamily(fontFamily); return *this; } \
  /** \
  * @brief Sets the font size of the text. \
  * \
  * @param[in] fontSize The font size in pixels. \
  */ \
  ChildClass& SetFontSize(float fontSize) { InputField::SetFontSize(fontSize); return *this; } \
  /** \
  * @brief Sets the color of the text. \
  * \
  * @param[in] color The required text color value. \
  */ \
  ChildClass& SetTextColor(const UiColor& color) { InputField::SetTextColor(color); return *this; } \
  /** \
  * @brief Sets the horizontal alignment of the text within the inputField. \
  * \
  * @param[in] alignment The horizontal text alignment. \
  */ \
  ChildClass& SetHorizontalTextAlignment(Text::Alignment alignment) { InputField::SetHorizontalTextAlignment(alignment); return *this; } \
  /** \
  * @brief Sets the vertical alignment of the text within the inputField. \
  * \
  * @param[in] alignment The vertical text alignment. \
  */ \
  ChildClass& SetVerticalTextAlignment(Text::Alignment alignment) { InputField::SetVerticalTextAlignment(alignment); return *this; } \
  /** \
  * @brief Sets the overflow mode. \
  * \
  * @param[in] mode The overflow mode to apply. \
  */ \
  ChildClass& SetOverflowMode(Text::OverflowMode mode) { InputField::SetOverflowMode(mode); return *this; } \
  /** \
  * @brief Sets the placeholder text displayed when the input field is empty. \
  * \
  * @param[in] text The placeholder text in UTF-8 encoding. \
  */ \
  ChildClass& SetPlaceholder(const Dali::String& text) { InputField::SetPlaceholder(text); return *this; } \
  /** \
  * @brief Sets the color of the placeholder text. \
  * \
  * @param[in] color The placeholder text color as a UiColor. \
  * \
  * @return A reference to this InputField for method chaining. \
  */ \
  ChildClass& SetPlaceholderColor(const UiColor& color) { InputField::SetPlaceholderColor(color); return *this; } \
  /** \
  * @brief Sets the width of the text cursor. \
  * \
  * @param[in] width The cursor width in pixels. \
  * \
  * @return A reference to this InputField for method chaining. \
  */ \
  ChildClass& SetCursorWidth(int width) { InputField::SetCursorWidth(width); return *this; } \
  /** \
  * @brief Sets the color of the text cursor \
  * \
  * This color is applied to both primary and secondary cursors \
  * when a split cursor is shown in bidirectional text. \
  * \
  * @param[in] color The cursor color as a UiColor. \
  * \
  * @return A reference to this InputField for method chaining. \
  */ \
  ChildClass& SetCursorColor(const UiColor& color) { InputField::SetCursorColor(color); return *this; } \
  /** \
  * @brief Sets the highlight color of the selected text region. \
  * \
  * @param[in] color The selection highlight color as a UiColor). \
  * \
  * @return A reference to this InputField for method chaining. \
  */ \
  ChildClass& SetSelectionColor(const UiColor& color) { InputField::SetSelectionColor(color); return *this; } \
  /** \
  * @brief Sets the maximum number of characters that can be entered into the InputField. \
  * \
  * @param[in] length The maximum number of characters allowed. \
  */ \
  ChildClass& SetMaximumLength(int length) { InputField::SetMaximumLength(length); return *this; } \
  /** \
  * @brief Sets how the layout direction of the text is resolved. \
  * \
  * - LayoutDirectionMode::CONTENTS: \
  *   The layout direction is determined from the text content itself. \
  * \
  * - LayoutDirectionMode::INHERIT: \
  *   The layout direction is inherited from the parent view. \
  * \
  * - LayoutDirectionMode::LOCALE: \
  *   The layout direction is determined based on the system locale. \
  * \
  * @note The default layout direction mode of InputField is LayoutDirectionMode::INHERIT. \
  * \
  * @param[in] mode The LayoutDirectionMode used to determine the text layout direction. \
  */ \
  ChildClass& SetLayoutDirectionMode(Text::LayoutDirectionMode mode) { InputField::SetLayoutDirectionMode(mode); return *this; } \
  /** \
  * @brief Sets the font weight. \
  * \
  * @param[in] weight The font weight. \
  */ \
  ChildClass& SetFontWeight(Text::FontWeight weight) { InputField::SetFontWeight(weight); return *this; } \
  /** \
  * @brief Sets the font width. \
  * \
  * @param[in] width The font width. \
  */ \
  ChildClass& SetFontWidth(Text::FontWidth width) { InputField::SetFontWidth(width); return *this; } \
  /** \
  * @brief Sets the font slant. \
  * \
  * @param[in] slant The font slant. \
  */ \
  ChildClass& SetFontSlant(Text::FontSlant slant) { InputField::SetFontSlant(slant); return *this; } \
  /** \
  * @brief Sets the underline style. \
  * \
  * @param[in] underline The underline configuration. \
  */ \
  ChildClass& SetUnderline(const Text::Underline& underline) { InputField::SetUnderline(underline); return *this; } \
  /** \
  * @brief Sets the shadow style. \
  * \
  * @param[in] shadow The shadow configuration. \
  */ \
  ChildClass& SetShadow(const Text::Shadow& shadow) { InputField::SetShadow(shadow); return *this; } \
  /** \
  * @brief Sets the outline style. \
  * \
  * @param[in] outline The outline configuration. \
  */ \
  ChildClass& SetOutline(const Text::Outline& outline) { InputField::SetOutline(outline); return *this; } \
  /** \
  * @brief Sets the line-through style. \
  * \
  * @param[in] lineThrough The line-through configuration. \
  */ \
  ChildClass& SetLineThrough(const Text::LineThrough& lineThrough) { InputField::SetLineThrough(lineThrough); return *this; } \
  /** \
  * @brief Sets the font size scale. \
  * \
  * The scaled font size is calculated from the current font size \
  * multiplied by this scale value. \
  * \
  * @param[in] scale The font size scale. \
  */ \
  ChildClass& SetFontSizeScale(float scale) { InputField::SetFontSizeScale(scale); return *this; } \
  /** \
  * @brief Sets the minimum font size scale. \
  * \
  * If this value is greater than the maximum font size scale, \
  * the adjusted font size scale follows this minimum value. \
  * \
  * @param[in] scale The minimum font size scale. \
  */ \
  ChildClass& SetMinimumFontSizeScale(float scale) { InputField::SetMinimumFontSizeScale(scale); return *this; } \
  /** \
  * @brief Sets the maximum font size scale. \
  * \
  * If this value is less than the minimum font size scale, \
  * the adjusted font size scale follows the minimum font size scale. \
  * \
  * @param[in] scale The maximum font size scale. \
  */ \
  ChildClass& SetMaximumFontSizeScale(float scale) { InputField::SetMaximumFontSizeScale(scale); return *this; } \
  /** \
  * @brief Sets whether the system font size scale is applied. \
  * \
  * When enabled, the system font size scale is used instead of \
  * the user-defined font size scale before applying the minimum \
  * and maximum constraints. \
  * \
  * @param[in] enabled True to apply the system font size scale, false otherwise. \
  */ \
  ChildClass& SetSystemFontSizeScaleEnabled(bool enabled) { InputField::SetSystemFontSizeScaleEnabled(enabled); return *this; }

#endif // DALI_UI_CHAIN_INPUTFIELD_METHODS
