// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_INTERACTIVEVIEW_METHODS(ChildClass) \
  DALI_UI_CHAIN_VIEW_METHODS(ChildClass) \
  /** \
  * @brief Sets the pseudo disabled state. \
  * \
  * @param[in] pseudoDisabled True to set pseudo disabled \
  * @see InteractiveTrait::SetPseudoDisabled \
  */ \
  ChildClass& SetPseudoDisabled(bool pseudoDisabled) { InteractiveView::SetPseudoDisabled(pseudoDisabled); return *this; } \
  /** \
  * @brief Sets whether clicking is allowed. \
  * \
  * @param[in] clickable True to allow clicking \
  * @see InteractiveTrait::SetClickable \
  */ \
  ChildClass& SetClickable(bool clickable) { InteractiveView::SetClickable(clickable); return *this; } \
  /** \
  * @brief Sets the key click policy. \
  * \
  * @param[in] policy The KeyClickPolicy to apply \
  * @see InteractiveTrait::SetKeyClickPolicy \
  */ \
  ChildClass& SetKeyClickPolicy(KeyClickPolicy policy) { InteractiveView::SetKeyClickPolicy(policy); return *this; } \
  /** \
  * @brief Connects a handler to ClickedSignal. \
  * \
  * Multiple calls accumulate — each call adds an additional handler. \
  * If @p obj implements ConnectionTrackerInterface (e.g. inherits ConnectionTracker), \
  * the connection is automatically removed when @p obj is destroyed. \
  * \
  * Supports member functions and stateless lambdas: \
  * @code \
  * view.ConnectClickedSignal(this, &MyClass::OnButtonClicked); \
  * view.ConnectClickedSignal(this, [](View v, const InputEvent& e) { ... }); \
  * @endcode \
  * \
  * @param[in] obj  The object to connect to (must implement ConnectionTrackerInterface for auto-disconnect) \
  * @param[in] func Member function pointer or functor with signature void(View, const InputEvent&) \
  * @return Reference to this for method chaining \
  */ \
  template<typename T, typename Func> \
  ChildClass& ConnectClickedSignal(T* obj, Func func) { InteractiveView::ConnectClickedSignal(obj, func); return *this; } \
  /** \
  * @brief Connects a handler to PressedChangedSignal. \
  * \
  * Multiple calls accumulate — each call adds an additional handler. \
  * The handler is called with @c pressed=true on press-down and @c pressed=false on release. \
  * If @p obj implements ConnectionTrackerInterface, the connection is auto-removed on @p obj destruction. \
  * \
  * @param[in] obj  The object to connect to \
  * @param[in] func Member function pointer or functor with signature void(View, bool, const InputEvent&) \
  * @return Reference to this for method chaining \
  */ \
  template<typename T, typename Func> \
  ChildClass& ConnectPressedChangedSignal(T* obj, Func func) { InteractiveView::ConnectPressedChangedSignal(obj, func); return *this; } \
  /** \
  * @brief Connects a handler to LongPressedSignal. \
  * \
  * Multiple calls accumulate — each call adds an additional handler. \
  * Long press fires once when the gesture is detected (on press-down after the time threshold). \
  * Press release is reported separately via PressedChangedSignal. \
  * \
  * The handler must return bool: return @c true to suppress the subsequent click event, \
  * or @c false to allow it. \
  * \
  * If @p obj implements ConnectionTrackerInterface, the connection is auto-removed on @p obj destruction. \
  * \
  * @param[in] obj  The object to connect to \
  * @param[in] func Member function pointer or functor with signature bool(View, const InputEvent&) \
  * @return Reference to this for method chaining \
  */ \
  template<typename T, typename Func> \
  ChildClass& ConnectLongPressedSignal(T* obj, Func func) { InteractiveView::ConnectLongPressedSignal(obj, func); return *this; }
