// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_LABEL_METHODS(ChildClass) \
  DALI_UI_CHAIN_VIEW_METHODS(ChildClass) \
  /** \
  * @brief Sets the text. \
  * \
  * @param[in] text The text to display in UTF-8 format. \
  */ \
  ChildClass& SetText(const Dali::String& text) { Label::SetText(text); return *this; } \
  /** \
  * @brief Sets the font family of the text. \
  * \
  * @param[in] fontFamily The requested font family to use. \
  */ \
  ChildClass& SetFontFamily(const Dali::String& fontFamily) { Label::SetFontFamily(fontFamily); return *this; } \
  /** \
  * @brief Sets the font size of the text. \
  * \
  * @param[in] fontSize The font size in pixels. \
  */ \
  ChildClass& SetFontSize(float fontSize) { Label::SetFontSize(fontSize); return *this; } \
  /** \
  * @brief Sets whether the text should be multi-line. \
  * \
  * @param[in] multiLine True for multi-line layout, false for single-line layout. \
  */ \
  ChildClass& SetMultiLine(bool multiLine) { Label::SetMultiLine(multiLine); return *this; } \
  /** \
  * @brief Sets the line wrap mode. \
  * \
  * @param[in] mode The line wrap mode to apply. \
  */ \
  ChildClass& SetLineWrapMode(Text::LineWrapMode mode) { Label::SetLineWrapMode(mode); return *this; } \
  /** \
  * @brief Sets the color of the text. \
  * \
  * @param[in] color The required text color value. \
  */ \
  ChildClass& SetTextColor(const UiColor& color) { Label::SetTextColor(color); return *this; } \
  /** \
  * @brief Sets the horizontal alignment of the text within the label. \
  * \
  * @param[in] alignment The horizontal text alignment. \
  */ \
  ChildClass& SetHorizontalTextAlignment(Text::Alignment alignment) { Label::SetHorizontalTextAlignment(alignment); return *this; } \
  /** \
  * @brief Sets the vertical alignment of the text within the label. \
  * \
  * @param[in] alignment The vertical text alignment. \
  */ \
  ChildClass& SetVerticalTextAlignment(Text::Alignment alignment) { Label::SetVerticalTextAlignment(alignment); return *this; } \
  /** \
  * @brief Sets the overflow mode. \
  * \
  * @param[in] mode The overflow mode to apply. \
  */ \
  ChildClass& SetOverflowMode(Text::OverflowMode mode) { Label::SetOverflowMode(mode); return *this; } \
  /** \
  * @brief Sets the line height of the text. \
  * \
  * The interpretation of this value depends on the current LineHeightMode. \
  * \
  * - If the mode is LineHeightMode::RELATIVE, the line height is calculated \
  *   as a multiplier of the font pixel size: \
  *   @code \
  *   CalculatedLineHeight(px) = FontSize(px) * lineHeight \
  *   @endcode \
  * \
  * - If the mode is LineHeightMode::ABSOLUTE, the value is treated as \
  *   an absolute line height in pixels. \
  * \
  * Setting lineHeight to -1.0f ensures enough vertical space to display \
  * the full font metrics (NaturalSize). This behavior is similar to the \
  * "Auto" line height option in design tools such as Figma. \
  * \
  * @note The final line height is clamped to be no smaller than \
  *       the natural line height derived from the font metrics. \
  * \
  * @param[in] lineHeight The line height value. \
  */ \
  ChildClass& SetLineHeight(float lineHeight) { Label::SetLineHeight(lineHeight); return *this; } \
  /** \
  * @brief Sets how the line height value is interpreted. \
  * \
  * - LineHeightMode::RELATIVE: \
  *   The line height is calculated as a multiplier of the font size. \
  * \
  * - LineHeightMode::ABSOLUTE: \
  *   The line height is treated as an absolute pixel value. \
  * \
  * The default mode is LineHeightMode::RELATIVE. \
  * \
  * @param[in] mode The line height mode. \
  */ \
  ChildClass& SetLineHeightMode(Text::LineHeightMode mode) { Label::SetLineHeightMode(mode); return *this; } \
  /** \
  * @brief Sets how the layout direction of the text is resolved. \
  * \
  * - LayoutDirectionMode::CONTENTS: \
  *   The layout direction is determined from the text content itself. \
  * \
  * - LayoutDirectionMode::INHERIT: \
  *   The layout direction is inherited from the parent view. \
  * \
  * - LayoutDirectionMode::LOCALE: \
  *   The layout direction is determined based on the system locale. \
  * \
  * @param[in] mode The LayoutDirectionMode used to determine the text layout direction. \
  */ \
  ChildClass& SetLayoutDirectionMode(Text::LayoutDirectionMode mode) { Label::SetLayoutDirectionMode(mode); return *this; } \
  /** \
  * @brief Enables or disables mark-up processing for the text. \
  * \
  * @param[in] enabled True to enable mark-up parsing, false to render text as plain string. \
  */ \
  ChildClass& SetMarkupEnabled(bool enabled) { Label::SetMarkupEnabled(enabled); return *this; } \
  /** \
  * @brief Sets the color of anchors in the text. \
  * \
  * @param[in] color The color to apply to anchors. \
  */ \
  ChildClass& SetAnchorColor(const UiColor& color) { Label::SetAnchorColor(color); return *this; } \
  /** \
  * @brief Sets the color of anchors when they are clicked. \
  * \
  * @param[in] color The color to apply to clicked anchors. \
  */ \
  ChildClass& SetAnchorClickedColor(const UiColor& color) { Label::SetAnchorClickedColor(color); return *this; } \
  /** \
  * @brief Sets the marquee speed. \
  * \
  * @param[in] speed The marquee speed in pixels per second. \
  */ \
  ChildClass& SetMarqueeSpeed(int speed) { Label::SetMarqueeSpeed(speed); return *this; } \
  /** \
  * @brief Sets the number of complete loops for marquee. \
  * \
  * @param[in] loopCount The number of loops. \
  */ \
  ChildClass& SetMarqueeLoopCount(int loopCount) { Label::SetMarqueeLoopCount(loopCount); return *this; } \
  /** \
  * @brief Sets the amount of time to delay the start of marquee and further loops. \
  * \
  * @param[in] delay The delay time in seconds. \
  */ \
  ChildClass& SetMarqueeLoopDelay(float delay) { Label::SetMarqueeLoopDelay(delay); return *this; } \
  /** \
  * @brief Sets the gap before marquee wraps. \
  * \
  * @param[in] gap The gap in pixels. \
  */ \
  ChildClass& SetMarqueeGap(int gap) { Label::SetMarqueeGap(gap); return *this; } \
  /** \
  * @brief Sets how the marquee stops. \
  * \
  * @param[in] stopMode The marquee stop mode. \
  */ \
  ChildClass& SetMarqueeStopMode(Text::MarqueeStopMode stopMode) { Label::SetMarqueeStopMode(stopMode); return *this; } \
  /** \
  * @brief Sets the marquee orientation. \
  * \
  * @param[in] orientation The marquee orientation. \
  */ \
  ChildClass& SetMarqueeOrientation(Text::MarqueeOrientation orientation) { Label::SetMarqueeOrientation(orientation); return *this; } \
  /** \
  * @brief Sets the font weight. \
  * \
  * @param[in] weight The font weight. \
  */ \
  ChildClass& SetFontWeight(Text::FontWeight weight) { Label::SetFontWeight(weight); return *this; } \
  /** \
  * @brief Sets the font width. \
  * \
  * @param[in] width The font width. \
  */ \
  ChildClass& SetFontWidth(Text::FontWidth width) { Label::SetFontWidth(width); return *this; } \
  /** \
  * @brief Sets the font slant. \
  * \
  * @param[in] slant The font slant. \
  */ \
  ChildClass& SetFontSlant(Text::FontSlant slant) { Label::SetFontSlant(slant); return *this; } \
  /** \
  * @brief Sets the background color behind the text. \
  * \
  * The background is rendered behind the glyphs of the text. \
  * \
  * @param[in] color The text background color. \
  * \
  * @return This label. \
  */ \
  ChildClass& SetTextBackgroundColor(const UiColor& color) { Label::SetTextBackgroundColor(color); return *this; } \
  /** \
  * @brief Sets the underline style. \
  * \
  * @param[in] underline The underline configuration. \
  */ \
  ChildClass& SetUnderline(const Text::Underline& underline) { Label::SetUnderline(underline); return *this; } \
  /** \
  * @brief Sets the shadow style. \
  * \
  * @param[in] shadow The shadow configuration. \
  */ \
  ChildClass& SetShadow(const Text::Shadow& shadow) { Label::SetShadow(shadow); return *this; } \
  /** \
  * @brief Sets the outline style. \
  * \
  * @param[in] outline The outline configuration. \
  */ \
  ChildClass& SetOutline(const Text::Outline& outline) { Label::SetOutline(outline); return *this; } \
  /** \
  * @brief Sets the line-through style. \
  * \
  * @param[in] lineThrough The line-through configuration. \
  */ \
  ChildClass& SetLineThrough(const Text::LineThrough& lineThrough) { Label::SetLineThrough(lineThrough); return *this; } \
  /** \
  * @brief Sets the bevel style. \
  * \
  * @param[in] bevel The bevel configuration. \
  */ \
  ChildClass& SetBevel(const Text::Bevel& bevel) { Label::SetBevel(bevel); return *this; } \
  /** \
  * @brief Sets the text fit range. \
  * \
  * Text fit selects the largest font size within the configured range \
  * that fits into the available layout space. \
  * \
  * @note Text fit is designed for bounded layout sizes. It is recommended to \
  * explicitly specify width and height when using this feature. \
  * When width or height is WRAP_CONTENT, measurement is performed using the \
  * maximum font size in the configured range. \
  * \
  * @param[in] range The text fit range configuration. \
  */ \
  ChildClass& SetTextFit(const Text::FitRange& range) { Label::SetTextFit(range); return *this; } \
  /** \
  * @brief Sets the text fit candidates. \
  * \
  * Text fit selects the largest candidate that fits into the available \
  * layout space. Each candidate defines a font size and line height. \
  * \
  * @note Text fit is designed for bounded layout sizes. It is recommended to \
  * explicitly specify width and height when using this feature. \
  * When width or height is WRAP_CONTENT, measurement uses the maximum fit \
  * candidate to determine the size. The maximum candidate is selected by the \
  * largest font size, and if equal, by the larger line height. \
  * \
  * @param[in] candidates The vector of text fit candidates. \
  */ \
  ChildClass& SetTextFit(const Dali::Vector<Text::FitCandidate>& candidates) { Label::SetTextFit(candidates); return *this; } \
  /** \
  * @brief Sets the font size scale. \
  * \
  * The scaled font size is calculated from the current font size \
  * multiplied by this scale value. \
  * \
  * @param[in] scale The font size scale. \
  */ \
  ChildClass& SetFontSizeScale(float scale) { Label::SetFontSizeScale(scale); return *this; } \
  /** \
  * @brief Sets the minimum font size scale. \
  * \
  * If this value is greater than the maximum font size scale, \
  * the adjusted font size scale follows this minimum value. \
  * \
  * @param[in] scale The minimum font size scale. \
  */ \
  ChildClass& SetMinimumFontSizeScale(float scale) { Label::SetMinimumFontSizeScale(scale); return *this; } \
  /** \
  * @brief Sets the maximum font size scale. \
  * \
  * If this value is less than the minimum font size scale, \
  * the adjusted font size scale follows the minimum font size scale. \
  * \
  * @param[in] scale The maximum font size scale. \
  */ \
  ChildClass& SetMaximumFontSizeScale(float scale) { Label::SetMaximumFontSizeScale(scale); return *this; } \
  /** \
  * @brief Sets whether the system font size scale is applied. \
  * \
  * When enabled, the system font size scale is combined with the current \
  * font size scale before applying the minimum and maximum constraints. \
  * \
  * @param[in] enabled True to apply the system font size scale, false otherwise. \
  */ \
  ChildClass& SetSystemFontSizeScaleEnabled(bool enabled) { Label::SetSystemFontSizeScaleEnabled(enabled); return *this; } \
  /** \
  * @brief Sets the font variation axes. \
  * \
  * This replaces all previously set font variation axes. \
  * \
  * If duplicate axis tags are provided, the last value is used. \
  * \
  * Unsupported axis tags may be ignored depending on the selected font. \
  * \
  * @param[in] axes The font variation axes. \
  * @return A reference to this label. \
  */ \
  ChildClass& SetFontVariation(const Dali::Vector<Text::FontVariationAxis>& axes) { Label::SetFontVariation(axes); return *this; } \
  /** \
  * @brief Sets the font variation from a settings string. \
  * \
  * The settings string consists of one or more pairs of axis tags and \
  * numeric values separated by commas. \
  * \
  * Supported formats include: \
  * - wght=700,wdth=90 (recommended) \
  * - "wght" 700, "wdth" 90 \
  * - 'wght' 700, 'wdth' 90 \
  * \
  * In quoted formats, the axis tag must be wrapped with single quotes \
  * (U+0027) or double quotes (U+0022). \
  * \
  * Each axis tag must contain exactly four printable ASCII characters \
  * in the range U+0020..U+007E. Space is allowed only as trailing \
  * characters in the axis tag. \
  * \
  * If duplicate axis tags are specified, the last value is used. \
  * \
  * If the input string is invalid, the font variation is not changed. \
  * \
  * Unsupported axis tags may be ignored depending on the selected font. \
  * \
  * @param[in] settings The font variation settings string. \
  * @return A reference to this label. \
  */ \
  ChildClass& SetFontVariation(const Dali::String& settings) { Label::SetFontVariation(settings); return *this; }
