// Generated by dali-ui preprocessor. Do not modify.
#ifndef DALI_UI_CHAIN_SCROLLVIEW_METHODS

#define DALI_UI_CHAIN_SCROLLVIEW_METHODS(ChildClass) \
  DALI_UI_CHAIN_VIEW_METHODS(ChildClass) \
  /** \
  * @brief Sets the content view to be scrolled. \
  * \
  * @param[in] content The content view \
  */ \
  ChildClass& SetContent(View content) { ScrollView::SetContent(content); return *this; } \
  /** \
  * @brief Sets the scroll position. \
  * \
  * @param[in] position The scroll position to set \
  */ \
  ChildClass& SetScrollPosition(const Vector2& position) { ScrollView::SetScrollPosition(position); return *this; } \
  /** \
  * @brief Sets the direction of the scroll. \
  * \
  * @param[in] direction The scroll direction \
  */ \
  ChildClass& SetScrollDirection(ScrollDirection direction) { ScrollView::SetScrollDirection(direction); return *this; } \
  /** \
  * @brief Sets the maximum distance by fling action. \
  * \
  * @param[in] distance The maximum fling distance \
  */ \
  ChildClass& SetMaxFlingDistance(float distance) { ScrollView::SetMaxFlingDistance(distance); return *this; } \
  /** \
  * @brief Sets the minimum duration of fling scroll animation. \
  * \
  * @param[in] duration The minimum fling duration \
  */ \
  ChildClass& SetMinimumFlingDuration(int duration) { ScrollView::SetMinimumFlingDuration(duration); return *this; } \
  /** \
  * @brief Sets the maximum duration of fling scroll animation. \
  * \
  * @param[in] duration The maximum fling duration \
  */ \
  ChildClass& SetMaximumFlingDuration(int duration) { ScrollView::SetMaximumFlingDuration(duration); return *this; } \
  /** \
  * @brief Sets the sensitivity of fling action. \
  * \
  * @param[in] sensitivity The fling sensitivity \
  */ \
  ChildClass& SetFlingSensitivity(float sensitivity) { ScrollView::SetFlingSensitivity(sensitivity); return *this; } \
  /** \
  * @brief Sets the deceleration rate of fling. \
  * \
  * @param[in] rate The deceleration rate \
  */ \
  ChildClass& SetDecelerationRate(float rate) { ScrollView::SetDecelerationRate(rate); return *this; } \
  /** \
  * @brief Sets the over scroll mode. \
  * \
  * @param[in] mode The over scroll mode \
  */ \
  ChildClass& SetOverScrollMode(OverScrollMode mode) { ScrollView::SetOverScrollMode(mode); return *this; } \
  /** \
  * @brief Sets the visibility of the vertical scroll bar. \
  * \
  * @param[in] visibility The vertical scroll bar visibility \
  */ \
  ChildClass& SetVerticalScrollBarVisibility(ScrollBarVisibility visibility) { ScrollView::SetVerticalScrollBarVisibility(visibility); return *this; } \
  /** \
  * @brief Sets the visibility of the horizontal scroll bar. \
  * \
  * @param[in] visibility The horizontal scroll bar visibility \
  */ \
  ChildClass& SetHorizontalScrollBarVisibility(ScrollBarVisibility visibility) { ScrollView::SetHorizontalScrollBarVisibility(visibility); return *this; }

#endif // DALI_UI_CHAIN_SCROLLVIEW_METHODS
