// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_UICONFIG_METHODS(ChildClass) \
  /** \
  * @brief Sets the scaling factor applied to spx and sdp units. \
  * \
  * @pre The config must not be frozen (i.e. not yet call UiConfig::Apply()). \
  * @param[in] scalingFactor The scaling factor value \
  */ \
  ChildClass& SetScalingFactor(float scalingFactor) { UiConfig::SetScalingFactor(scalingFactor); return *this; } \
  /** \
  * @brief Sets the screen DPI used for dp and sdp unit calculations. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] dpi The dots-per-inch value of the target display \
  */ \
  ChildClass& SetDpi(int dpi) { UiConfig::SetDpi(dpi); return *this; } \
  /** \
  * @brief Sets the baseline DPI used as the reference for dp calculations. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] baselineDpi The baseline dots-per-inch value \
  */ \
  ChildClass& SetBaselineDpi(int baselineDpi) { UiConfig::SetBaselineDpi(baselineDpi); return *this; } \
  /** \
  * @brief Sets the default key click policy for clickable views. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] policy The key click policy \
  */ \
  ChildClass& SetKeyClickPolicy(KeyClickPolicy policy) { UiConfig::SetKeyClickPolicy(policy); return *this; } \
  /** \
  * @brief Sets the predicate used to determine whether a key event triggers \
  * click execution (e.g. "Return", "KP_Enter"). \
  * \
  * When a key event is received by a clickable View, this predicate is called \
  * with the key name. If it returns @c true, the View treats the key as a \
  * click execution key and fires the click action. The default predicate \
  * matches "Return" only. \
  * \
  * @note This parameter is a plain function pointer (ExecutionKeyPredicate). \
  * Lambdas with captures and member function pointers are not accepted. \
  * Only free functions or stateless lambdas may be used. \
  * \
  * @note Passing @c nullptr restores the default predicate that matches "Return". \
  * \
  * @pre The config must not be frozen (i.e. Apply() must not have been called). \
  * Calling this method after Apply() triggers an assert in debug builds and \
  * is ignored in release builds. \
  * \
  * @param[in] predicate A function pointer matching the ExecutionKeyPredicate \
  *                      signature, or @c nullptr to restore the default \
  * @return Reference to this UiConfig for method chaining \
  * \
  * @code \
  *   bool MyKeyPredicate(const Dali::String& keyName) { \
  *     return keyName == "Return" || keyName == "KP_Enter"; \
  *   } \
  *   UiConfig::New() \
  *     .SetExecutionKeyPredicate(MyKeyPredicate) \
  *     .Apply(); \
  * @endcode \
  */ \
  ChildClass& SetExecutionKeyPredicate(ExecutionKeyPredicate predicate) { UiConfig::SetExecutionKeyPredicate(predicate); return *this; } \
  /** \
  * @brief Sets the threshold for recognizing a key long-press. \
  * \
  * When a key is held down, the system generates repeated key press events. \
  * This threshold defines how many consecutive key press events must be \
  * received before the input is recognized as a long-press action. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] threshold The minimum number of consecutive key press events \
  *                      required to trigger a long-press \
  */ \
  ChildClass& SetKeyLongPressThreshold(uint32_t threshold) { UiConfig::SetKeyLongPressThreshold(threshold); return *this; } \
  /** \
  * @brief Sets the tap recognizer time limit in milliseconds. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] timeMs The time limit in milliseconds \
  */ \
  ChildClass& SetTapRecognizerTime(uint32_t timeMs) { UiConfig::SetTapRecognizerTime(timeMs); return *this; } \
  /** \
  * @brief Sets an image to be displayed when image loading fails. \
  * \
  * This method configures a broken image that will be shown in image views (e.g., ImageView) \
  * when the requested image fails to load properly. Using different broken image types \
  * allows for appropriate broken images based on the target view size. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] brokenImageType The type of broken image (SMALL, NORMAL, or LARGE) \
  * @param[in] brokenImageUrl The URL of the broken image to use \
  */ \
  ChildClass& SetBrokenImageUrl(BrokenImageType brokenImageType, const Dali::String& brokenImageUrl) { UiConfig::SetBrokenImageUrl(brokenImageType, brokenImageUrl); return *this; } \
  /** \
  * @brief Sets whether to clear focus when the Escape key is pressed. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] enable True to enable focus clearing on Escape key \
  * @return Reference to this for method chaining \
  */ \
  ChildClass& EnableFocusClearOnEscape(bool enable) { UiConfig::EnableFocusClearOnEscape(enable); return *this; } \
  /** \
  * @brief Sets whether to always show the keyboard focus indicator. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] alwaysShow True to always show focus indicator \
  * @return Reference to this for method chaining \
  */ \
  ChildClass& SetAlwaysShowFocus(bool alwaysShow) { UiConfig::SetAlwaysShowFocus(alwaysShow); return *this; } \
  /** \
  * @brief Sets the default font point-size for text elements. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] fontSize The default font size in points \
  */ \
  ChildClass& SetDefaultFontSize(float fontSize) { UiConfig::SetDefaultFontSize(fontSize); return *this; } \
  /** \
  * @brief Sets the default text color for text elements. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] color The default text color \
  */ \
  ChildClass& SetDefaultTextColor(const Vector4& color) { UiConfig::SetDefaultTextColor(color); return *this; } \
  /** \
  * @brief Sets the default placeholder text color. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] color The default placeholder text color. \
  */ \
  ChildClass& SetDefaultPlaceholderTextColor(const Vector4& color) { UiConfig::SetDefaultPlaceholderTextColor(color); return *this; } \
  /** \
  * @brief Sets whether the placeholder text is shown when the control has focus. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] enabled True to show the placeholder text when focused, false otherwise. \
  */ \
  ChildClass& SetShowPlaceholderTextOnFocus(bool enabled) { UiConfig::SetShowPlaceholderTextOnFocus(enabled); return *this; } \
  /** \
  * @brief Sets the marquee speed in pixels per second. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] speed The marquee speed in pixels per second \
  */ \
  ChildClass& SetMarqueeSpeed(int speed) { UiConfig::SetMarqueeSpeed(speed); return *this; } \
  /** \
  * @brief Sets the number of complete loops for marquee. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] loopCount The number of loops \
  */ \
  ChildClass& SetMarqueeLoopCount(int loopCount) { UiConfig::SetMarqueeLoopCount(loopCount); return *this; } \
  /** \
  * @brief Sets the amount of time to delay the start of marquee and further loops. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] delay The delay time in seconds \
  */ \
  ChildClass& SetMarqueeLoopDelay(float delay) { UiConfig::SetMarqueeLoopDelay(delay); return *this; } \
  /** \
  * @brief Sets the gap before marquee wraps. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] gap The gap in pixels \
  */ \
  ChildClass& SetMarqueeGap(float gap) { UiConfig::SetMarqueeGap(gap); return *this; } \
  /** \
  * @brief Sets the marquee stop behaviour. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] stopMode The marquee stop mode \
  */ \
  ChildClass& SetMarqueeStopMode(Text::MarqueeStopMode stopMode) { UiConfig::SetMarqueeStopMode(stopMode); return *this; } \
  /** \
  * @brief Sets the marquee orientation. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] orientation The marquee orientation \
  */ \
  ChildClass& SetMarqueeOrientation(Text::MarqueeOrientation orientation) { UiConfig::SetMarqueeOrientation(orientation); return *this; } \
  /** \
  * @brief Sets whether Label uses asynchronous text rendering by default. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] asyncRendering True to enable asynchronous rendering for Label by default, \
  * false to use synchronous rendering. \
  */ \
  ChildClass& SetLabelAsyncRendering(bool asyncRendering) { UiConfig::SetLabelAsyncRendering(asyncRendering); return *this; }
