// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_UICONFIG_METHODS(ChildClass) \
  /** \
  * @brief Sets the scaling factor applied to spx and sdp units. \
  * \
  * @pre The config must not be frozen (i.e. not yet call UiConfig::Apply()). \
  * @param[in] scalingFactor The scaling factor value \
  */ \
  ChildClass& SetScalingFactor(float scalingFactor) { UiConfig::SetScalingFactor(scalingFactor); return *this; } \
  /** \
  * @brief Sets the screen DPI used for dp and sdp unit calculations. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] dpi The dots-per-inch value of the target display \
  */ \
  ChildClass& SetDpi(int dpi) { UiConfig::SetDpi(dpi); return *this; } \
  /** \
  * @brief Sets the baseline DPI used as the reference for dp calculations. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] baselineDpi The baseline dots-per-inch value \
  */ \
  ChildClass& SetBaselineDpi(int baselineDpi) { UiConfig::SetBaselineDpi(baselineDpi); return *this; } \
  /** \
  * @brief Sets the default key click policy for clickable views. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] policy The key click policy \
  */ \
  ChildClass& SetKeyClickPolicy(KeyClickPolicy policy) { UiConfig::SetKeyClickPolicy(policy); return *this; } \
  /** \
  * @brief Sets the predicate used to determine whether a key event triggers \
  * click execution (e.g. "Return", "KP_Enter"). \
  * \
  * When a key event is received by a clickable View, this predicate is called \
  * with the key name. If it returns @c true, the View treats the key as a \
  * click execution key and fires the click action. The default predicate \
  * matches "Return" only. \
  * \
  * @note This parameter is a plain function pointer (ExecutionKeyPredicate). \
  * Lambdas with captures and member function pointers are not accepted. \
  * Only free functions or stateless lambdas may be used. \
  * \
  * @note Passing @c nullptr restores the default predicate that matches "Return". \
  * \
  * @pre The config must not be frozen (i.e. Apply() must not have been called). \
  * Calling this method after Apply() triggers an assert in debug builds and \
  * is ignored in release builds. \
  * \
  * @param[in] predicate A function pointer matching the ExecutionKeyPredicate \
  *                      signature, or @c nullptr to restore the default \
  * @return Reference to this UiConfig for method chaining \
  * \
  * @code \
  *   bool MyKeyPredicate(const std::string& keyName) { \
  *     return keyName == "Return" || keyName == "KP_Enter"; \
  *   } \
  *   UiConfig::New() \
  *     .SetExecutionKeyPredicate(MyKeyPredicate) \
  *     .Apply(); \
  * @endcode \
  */ \
  ChildClass& SetExecutionKeyPredicate(ExecutionKeyPredicate predicate) { UiConfig::SetExecutionKeyPredicate(predicate); return *this; } \
  /** \
  * @brief Sets the minimum key repeat count to trigger a long-press via key input. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] count The minimum repeat count \
  */ \
  ChildClass& SetMinLongPressKeyCount(uint32_t count) { UiConfig::SetMinLongPressKeyCount(count); return *this; } \
  /** \
  * @brief Sets the tap recognizer time limit in milliseconds. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] timeMs The time limit in milliseconds \
  */ \
  ChildClass& SetTapRecognizerTime(uint32_t timeMs) { UiConfig::SetTapRecognizerTime(timeMs); return *this; }
