// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_VIEW_METHODS(ChildClass) \
  /** \
  * @brief Sets the X position of the View. \
  * \
  * @param[in] x The X position to set \
  */ \
  ChildClass& SetPositionX(float x) { View::SetPositionX(x); return *this; } \
  /** \
  * @brief Sets the Y position of the View. \
  * \
  * @param[in] y The Y position to set \
  */ \
  ChildClass& SetPositionY(float y) { View::SetPositionY(y); return *this; } \
  /** \
  * @brief Sets the parent origin of the View. \
  * \
  * @param[in] point The parent origin to set \
  */ \
  ChildClass& SetParentOrigin(const Vector3& point) { View::SetParentOrigin(point); return *this; } \
  /** \
  * @brief Sets the pivot point of the View. \
  * \
  * @param[in] point The pivot point to set \
  */ \
  ChildClass& SetPivotPoint(const Vector3& point) { View::SetPivotPoint(point); return *this; } \
  /** \
  * @brief Sets the requested width. \
  * \
  * A positive value sets a fixed width. \
  * WRAP_CONTENT (-1): sizes to content (default). \
  * MATCH_PARENT (-2): fills the parent container. \
  * \
  * @param[in] width The requested width \
  */ \
  ChildClass& SetRequestedWidth(float width) { View::SetRequestedWidth(width); return *this; } \
  /** \
  * @brief Sets the requested height. \
  * \
  * A positive value sets a fixed height. \
  * WRAP_CONTENT (-1): sizes to content (default). \
  * MATCH_PARENT (-2): fills the parent container. \
  * \
  * @param[in] height The requested height \
  */ \
  ChildClass& SetRequestedHeight(float height) { View::SetRequestedHeight(height); return *this; } \
  /** \
  * @brief Sets the minimum width. \
  * \
  * @param[in] width The minimum width \
  */ \
  ChildClass& SetMinimumWidth(float width) { View::SetMinimumWidth(width); return *this; } \
  /** \
  * @brief Sets the minimum height. \
  * \
  * @param[in] height The minimum height \
  */ \
  ChildClass& SetMinimumHeight(float height) { View::SetMinimumHeight(height); return *this; } \
  /** \
  * @brief Sets the maximum width. \
  * \
  * @param[in] width The maximum width \
  */ \
  ChildClass& SetMaximumWidth(float width) { View::SetMaximumWidth(width); return *this; } \
  /** \
  * @brief Sets the maximum height. \
  * \
  * @param[in] height The maximum height \
  */ \
  ChildClass& SetMaximumHeight(float height) { View::SetMaximumHeight(height); return *this; } \
  /** \
  * @brief Sets the view margin. \
  * \
  * @param[in] margin The margin to set \
  */ \
  ChildClass& SetViewMargin(const Extents& margin) { View::SetViewMargin(margin); return *this; } \
  /** \
  * @brief Sets the view padding. \
  * \
  * @param[in] padding The padding to set \
  */ \
  ChildClass& SetViewPadding(const Extents& padding) { View::SetViewPadding(padding); return *this; } \
  /** \
  * @brief Sets whether the actor should be focusable by keyboard navigation. \
  * \
  * @param[in] focusable True if it is focusable \
  */ \
  ChildClass& SetFocusable(bool focusable) { View::SetFocusable(focusable); return *this; } \
  /** \
  * @brief Sets whether the actor should be focused when touched. \
  * \
  * @param[in] touchFocusable True if it gets focused when touched \
  */ \
  ChildClass& SetTouchFocusable(bool touchFocusable) { View::SetTouchFocusable(touchFocusable); return *this; } \
  /** \
  * @brief Sets the background color. \
  * \
  * If the UiColor has a color ID, it is resolved from the current \
  * theme and a binding is registered so the color is automatically \
  * refreshed when the theme changes. \
  * \
  * If the UiColor has direct RGBA values, it is applied immediately \
  * and any previous ID-based binding for this property is removed. \
  * \
  * @param[in] color The UiColor to apply \
  */ \
  ChildClass& SetBackgroundColor(const UiColor& color) { View::SetBackgroundColor(color); return *this; } \
  /** \
  * @brief Sets whether the view is enabled. \
  * \
  * A disabled view does not receive user interaction. Setting this to false \
  * adds the Disabled state and emits StateChangedSignal. \
  * \
  * @param[in] enabled True to enable, false to disable \
  */ \
  ChildClass& SetEnabled(bool enabled) { View::SetEnabled(enabled); return *this; } \
  /** \
  * @brief Attaches the interaction trait to this View and optionally configures it. \
  * \
  * A View can have at most one interaction trait for its lifetime; attaching interactive \
  * succeeds only if no other interaction trait is set. If the View already has an \
  * InteractiveTrait (e.g. from a previous AsInteractive call), the existing trait is \
  * used and the configure callback is invoked with it. \
  * \
  * The callback is invoked in the caller's translation unit, so no std::function \
  * crosses the library ABI boundary; this preserves ABI stability across toolchains. \
  * \
  * @param[in] configure Optional callback to configure the InteractiveTrait (e.g. connect signals). \
  *                     Can be null or omitted to only attach the trait. \
  * @return Reference to this View for fluent chaining \
  */ \
  ChildClass& AsInteractive(std::function<void(InteractiveTrait&)> configure = nullptr) { View::AsInteractive(configure); return *this; } \
  /** \
  * @brief Assigns this View instance to a target variable. \
  * This method is useful for capturing a reference to a View created within \
  * a declarative UI tree for later use. \
  */ \
  ChildClass& As(View& self) { View::As(self); return *this; } \
  /** \
  * @brief Executes a custom action on this View instance. \
  * Use this method to perform additional initialization or logic on a View \
  * without breaking the declarative method chaining. \
  * @param[in] action A function or lambda to be executed with this instance. \
  */ \
  ChildClass& With(std::function<void(View&)> action) { View::With(action); return *this; } \
  /** \
  * @brief Sets layout parameters on this View. \
  * \
  * The params handle is stored on the View as-is, and the View's \
  * measure cache is invalidated. \
  * \
  * @param[in] params The layout parameters to attach to this View \
  * @return Reference to this View for fluent chaining \
  * \
  * @code \
  * child.SetLayoutParams( \
  *   AbsoluteLayoutParams::New() \
  *     .SetBounds(LayoutRect(10, 20, 100, 200)) \
  *     .SetFlags(AbsoluteLayoutFlags::POSITION_PROPORTIONAL)); \
  * @endcode \
  */ \
  ChildClass& SetLayoutParams(LayoutParams params) { View::SetLayoutParams(params); return *this; } \
  /** \
  * @brief Adds a list of children to this View in a declarative way. \
  * This method allows for a hierarchical UI tree construction by passing \
  * a brace-enclosed initializer list of View objects. \
  * @param[in] children The initializer list containing child View handles to be added. \
  */ \
  ChildClass& Children(std::initializer_list<View> children) { View::Children(children); return *this; }
