// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_VIEW_METHODS(ChildClass) \
  /** \
  * @brief Sets the x scale factor applied to the view. \
  * \
  * @param[in] scaleX The X scale factor to set \
  */ \
  ChildClass& SetScaleX(float scaleX) { View::SetScaleX(scaleX); return *this; } \
  /** \
  * @brief Sets the UiScale participation policy for this view. \
  * \
  * @param[in] policy The UiScalePolicy to apply \
  * @return Reference to this View for fluent chaining \
  */ \
  ChildClass& SetUiScalePolicy(UiScalePolicy policy) { View::SetUiScalePolicy(policy); return *this; } \
  /** \
  * @brief Sets the y scale factor applied to the view. \
  * \
  * @param[in] scaleY The Y scale factor to set \
  */ \
  ChildClass& SetScaleY(float scaleY) { View::SetScaleY(scaleY); return *this; } \
  /** \
  * @brief Sets the y scale factor applied to the view. \
  * \
  * @param[in] scaleX The X scale factor to set \
  * @param[in] scaleY The Y scale factor to set \
  */ \
  ChildClass& SetScale(float scaleX, float scaleY) { View::SetScale(scaleX, scaleY); return *this; } \
  /** \
  * @brief Sets the visibility of the view. \
  * \
  * @param[in] visibility True to make the view visible, false to hide it \
  * @return Reference to this View for fluent chaining \
  */ \
  ChildClass& SetVisibility(bool visibility) { View::SetVisibility(visibility); return *this; } \
  /** \
  * @brief Sets the opacity of the view. \
  * \
  * @param[in] opacity The opacity value to set (0.0 to 1.0) \
  * @return Reference to this View for fluent chaining \
  */ \
  ChildClass& SetOpacity(float opacity) { View::SetOpacity(opacity); return *this; } \
  /** \
  * @brief Sets the X position requested by the user. \
  * \
  * This value is the layout input. The parent's Arrange pass uses it \
  * (offset by the parent's left padding and this view's left margin) to \
  * compute the final rendered position. The Actor::Property::POSITION_X \
  * property is updated only by the next Arrange. \
  * \
  * To drive the rendered position without affecting the layout request \
  * (e.g. for scrolling or animation that should not feed back into \
  * layout), set Actor::Property::POSITION_X via SetProperty directly. \
  * \
  * @param[in] x The requested X position \
  */ \
  ChildClass& SetRequestedPositionX(float x) { View::SetRequestedPositionX(x); return *this; } \
  /** \
  * @brief Sets the Y position requested by the user. \
  * \
  * @param[in] y The requested Y position \
  * @see SetRequestedPositionX \
  */ \
  ChildClass& SetRequestedPositionY(float y) { View::SetRequestedPositionY(y); return *this; } \
  /** \
  * @brief Sets the parent origin of the View. \
  * \
  * @param[in] point The parent origin to set \
  */ \
  ChildClass& SetParentOrigin(const Vector3& point) { View::SetParentOrigin(point); return *this; } \
  /** \
  * @brief Sets the pivot of the View. \
  * \
  * @param[in] point The pivot to set \
  */ \
  ChildClass& SetPivot(const Vector3& point) { View::SetPivot(point); return *this; } \
  /** \
  * @brief Sets the requested width. \
  * \
  * A positive value sets a fixed width. \
  * WRAP_CONTENT (-1): sizes to content (default). \
  * MATCH_PARENT (-2): fills the parent container. \
  * \
  * @param[in] width The requested width \
  */ \
  ChildClass& SetRequestedWidth(float width) { View::SetRequestedWidth(width); return *this; } \
  /** \
  * @brief Sets the requested height. \
  * \
  * A positive value sets a fixed height. \
  * WRAP_CONTENT (-1): sizes to content (default). \
  * MATCH_PARENT (-2): fills the parent container. \
  * \
  * @param[in] height The requested height \
  */ \
  ChildClass& SetRequestedHeight(float height) { View::SetRequestedHeight(height); return *this; } \
  /** \
  * @brief Sets the minimum width. \
  * \
  * @param[in] width The minimum width \
  */ \
  ChildClass& SetMinimumWidth(float width) { View::SetMinimumWidth(width); return *this; } \
  /** \
  * @brief Sets the minimum height. \
  * \
  * @param[in] height The minimum height \
  */ \
  ChildClass& SetMinimumHeight(float height) { View::SetMinimumHeight(height); return *this; } \
  /** \
  * @brief Sets the maximum width. \
  * \
  * @param[in] width The maximum width \
  */ \
  ChildClass& SetMaximumWidth(float width) { View::SetMaximumWidth(width); return *this; } \
  /** \
  * @brief Sets the maximum height. \
  * \
  * @param[in] height The maximum height \
  */ \
  ChildClass& SetMaximumHeight(float height) { View::SetMaximumHeight(height); return *this; } \
  /** \
  * @brief Sets the view margin. \
  * \
  * @param[in] margin The margin to set \
  */ \
  ChildClass& SetMargin(const Extents& margin) { View::SetMargin(margin); return *this; } \
  /** \
  * @brief Sets the view padding. \
  * \
  * @param[in] padding The padding to set \
  */ \
  ChildClass& SetPadding(const Extents& padding) { View::SetPadding(padding); return *this; } \
  /** \
  * @brief Sets the layout mode of this View. \
  * \
  * LayoutMode::DEFAULT (default) lets the parent container's layout system manage \
  * this View's size and position normally. \
  * \
  * LayoutMode::STANDALONE excludes this View from the parent's accumulation, \
  * spacing and index calculations. The View's size is still measured normally \
  * (so MATCH_PARENT, WRAP_CONTENT and explicit RequestedWidth/Height all work), \
  * but its position is taken from SetPositionX/SetPositionY instead of being \
  * decided by the parent layout. This is useful for floating overlays, drag \
  * previews, tooltips and absolute positioning inside any LayoutManager. \
  * \
  * Standalone children ignore the parent's padding entirely. Their measured \
  * size is the parent's full inner size minus the child's own margin, and \
  * their final position is SetPositionX/SetPositionY plus the child's own \
  * margin in the parent's coordinate space. This keeps size and position \
  * consistent: a Standalone child with MATCH_PARENT fills the parent edge \
  * to edge regardless of parent padding, and any margin set on the child \
  * shifts it inward in both axes. \
  * \
  * @param[in] mode The layout mode to set \
  */ \
  ChildClass& SetLayoutMode(LayoutMode mode) { View::SetLayoutMode(mode); return *this; } \
  /** \
  * @brief Sets whether the actor should be focusable by keyboard navigation. \
  * \
  * @param[in] focusable True if it is focusable \
  */ \
  ChildClass& SetFocusable(bool focusable) { View::SetFocusable(focusable); return *this; } \
  /** \
  * @brief Sets whether the actor should be focused when touched. \
  * \
  * @param[in] touchFocusable True if it gets focused when touched \
  */ \
  ChildClass& SetTouchFocusable(bool touchFocusable) { View::SetTouchFocusable(touchFocusable); return *this; } \
  /** \
  * @brief Sets whether descendant focus is blocked. \
  * \
  * When blocked, none of this View's descendants can receive keyboard focus. \
  * Focus requests on descendants will be rejected. \
  * \
  * @param[in] blocked True to block descendant focus \
  */ \
  ChildClass& SetDescendantFocusBlocked(bool blocked) { View::SetDescendantFocusBlocked(blocked); return *this; } \
  /** \
  * @brief Sets the left focusable View for keyboard navigation. \
  * \
  * @param[in] view The View to focus when navigating left \
  */ \
  ChildClass& SetLeftFocusableView(View view) { View::SetLeftFocusableView(view); return *this; } \
  /** \
  * @brief Sets the right focusable View for keyboard navigation. \
  * \
  * @param[in] view The View to focus when navigating right \
  */ \
  ChildClass& SetRightFocusableView(View view) { View::SetRightFocusableView(view); return *this; } \
  /** \
  * @brief Sets the up focusable View for keyboard navigation. \
  * \
  * @param[in] view The View to focus when navigating up \
  */ \
  ChildClass& SetUpFocusableView(View view) { View::SetUpFocusableView(view); return *this; } \
  /** \
  * @brief Sets the down focusable View for keyboard navigation. \
  * \
  * @param[in] view The View to focus when navigating down \
  */ \
  ChildClass& SetDownFocusableView(View view) { View::SetDownFocusableView(view); return *this; } \
  /** \
  * @brief Sets the clockwise focusable View for keyboard navigation. \
  * \
  * @param[in] view The View to focus when navigating clockwise \
  */ \
  ChildClass& SetClockwiseFocusableView(View view) { View::SetClockwiseFocusableView(view); return *this; } \
  /** \
  * @brief Sets the counter-clockwise focusable View for keyboard navigation. \
  * \
  * @param[in] view The View to focus when navigating counter-clockwise \
  */ \
  ChildClass& SetCounterClockwiseFocusableView(View view) { View::SetCounterClockwiseFocusableView(view); return *this; } \
  /** \
  * @brief Sets the forward focusable View for keyboard navigation. \
  * \
  * @param[in] view The View to focus when navigating forward \
  */ \
  ChildClass& SetForwardFocusableView(View view) { View::SetForwardFocusableView(view); return *this; } \
  /** \
  * @brief Sets the backward focusable View for keyboard navigation. \
  * \
  * @param[in] view The View to focus when navigating backward \
  */ \
  ChildClass& SetBackwardFocusableView(View view) { View::SetBackwardFocusableView(view); return *this; } \
  /** \
  * @brief Sets the background color. \
  * \
  * If the UiColor has a color ID, it is resolved from the current \
  * theme and a binding is registered so the color is automatically \
  * refreshed when the theme changes. \
  * \
  * If the UiColor has direct RGBA values, it is applied immediately \
  * and any previous ID-based binding for this property is removed. \
  * \
  * @param[in] color The UiColor to apply \
  */ \
  ChildClass& SetBackgroundColor(const UiColor& color) { View::SetBackgroundColor(color); return *this; } \
  /** \
  * @brief Sets the color. \
  * \
  * @param[in] color The color to set \
  * @return Reference to this View for fluent chaining \
  */ \
  ChildClass& SetColor(const UiColor& color) { View::SetColor(color); return *this; } \
  /** \
  * @brief Sets whether the view is enabled. \
  * \
  * A disabled view does not receive user interaction. Setting this to false \
  * adds the Disabled state and emits StateChangedSignal. \
  * \
  * @param[in] enabled True to enable, false to disable \
  */ \
  ChildClass& SetEnabled(bool enabled) { View::SetEnabled(enabled); return *this; } \
  /** \
  * @brief Sets a uniform corner radius for all four corners. \
  * \
  * @param[in] radius The corner radius to apply to all corners \
  */ \
  ChildClass& SetCornerRadius(float radius) { View::SetCornerRadius(radius); return *this; } \
  /** \
  * @brief Sets individual corner radii for all four corners. \
  * \
  * @param[in] topLeft     The radius for the top-left corner \
  * @param[in] topRight    The radius for the top-right corner \
  * @param[in] bottomRight The radius for the bottom-right corner \
  * @param[in] bottomLeft  The radius for the bottom-left corner \
  */ \
  ChildClass& SetCornerRadius(float topLeft, float topRight, float bottomRight, float bottomLeft) { View::SetCornerRadius(topLeft, topRight, bottomRight, bottomLeft); return *this; } \
  /** \
  * @brief Sets corner radii from a Vector4. \
  * \
  * @param[in] radius Corner radii as Vector4 (x=topLeft, y=topRight, z=bottomRight, w=bottomLeft) \
  */ \
  ChildClass& SetCornerRadius(const Vector4& radius) { View::SetCornerRadius(radius); return *this; } \
  /** \
  * @brief Sets the corner radius policy. \
  * \
  * @param[in] policy ABSOLUTE for world-unit values (default), RELATIVE for percentage [0.0, 0.5] of the shorter side \
  */ \
  ChildClass& SetCornerRadiusPolicy(CornerRadiusPolicy policy) { View::SetCornerRadiusPolicy(policy); return *this; } \
  /** \
  * @brief Shortcut to set the corner radius policy to RELATIVE. \
  * \
  * Equivalent to SetCornerRadiusPolicy(CornerRadiusPolicy::RELATIVE). \
  */ \
  ChildClass& SetCornerRadiusPolicyRelative() { View::SetCornerRadiusPolicyRelative(); return *this; } \
  /** \
  * @brief Sets a uniform corner squareness for all four corners. \
  * \
  * @param[in] squareness The squareness value to apply to all corners \
  */ \
  ChildClass& SetCornerSquareness(float squareness) { View::SetCornerSquareness(squareness); return *this; } \
  /** \
  * @brief Sets individual corner squareness values for all four corners. \
  * \
  * @param[in] topLeft     The squareness for the top-left corner \
  * @param[in] topRight    The squareness for the top-right corner \
  * @param[in] bottomRight The squareness for the bottom-right corner \
  * @param[in] bottomLeft  The squareness for the bottom-left corner \
  */ \
  ChildClass& SetCornerSquareness(float topLeft, float topRight, float bottomRight, float bottomLeft) { View::SetCornerSquareness(topLeft, topRight, bottomRight, bottomLeft); return *this; } \
  /** \
  * @brief Sets corner squareness from a Vector4. \
  * \
  * @param[in] squareness Squareness values as Vector4 (x=topLeft, y=topRight, z=bottomRight, w=bottomLeft) \
  */ \
  ChildClass& SetCornerSquareness(const Vector4& squareness) { View::SetCornerSquareness(squareness); return *this; } \
  /** \
  * @brief Sets the borderline width of the view. \
  * \
  * @param[in] width The borderline width to set \
  */ \
  ChildClass& SetBorderlineWidth(float width) { View::SetBorderlineWidth(width); return *this; } \
  /** \
  * @brief Sets the borderline color of the view. \
  * \
  * If the UiColor has a color ID, it is resolved from the current \
  * theme and a binding is registered so the color is automatically \
  * refreshed when the theme changes. \
  * \
  * @param[in] color The UiColor to apply \
  */ \
  ChildClass& SetBorderlineColor(const UiColor& color) { View::SetBorderlineColor(color); return *this; } \
  /** \
  * @brief Sets the borderline offset of the view. \
  * \
  * @param[in] offset The borderline offset to set \
  */ \
  ChildClass& SetBorderlineOffset(float offset) { View::SetBorderlineOffset(offset); return *this; } \
  /** \
  * @brief Sets the name of this view. \
  * \
  * @param[in] name The name to set \
  */ \
  ChildClass& SetName(const Dali::String& name) { View::SetName(name); return *this; } \
  /** \
  * @brief Sets the layout direction of this view explicitly. \
  * \
  * Overrides inherited direction from the parent. To revert to inheritance, \
  * use ClearLayoutDirection(). \
  * \
  * @param[in] direction The layout direction to set (LEFT_TO_RIGHT or RIGHT_TO_LEFT) \
  * @return Reference to this View for fluent chaining \
  */ \
  ChildClass& SetLayoutDirection(Dali::LayoutDirection::Type direction) { View::SetLayoutDirection(direction); return *this; } \
  /** \
  * @brief Attaches the interaction trait to this View. \
  * \
  * @return Reference to this View for fluent chaining \
  */ \
  ChildClass& AsInteractive() { View::AsInteractive(); return *this; } \
  /** \
  * @brief Attaches the interaction trait to this View and configures it. \
  * \
  * @param[in] configure Callable with signature void(InteractiveTrait&) \
  * @return Reference to this View for fluent chaining \
  */ \
  template<typename F> \
  ChildClass& AsInteractive(F&& configure) { View::AsInteractive(configure); return *this; } \
  /** \
  * @brief Attaches the selectable trait to this View. \
  * \
  * A View can have at most one selectable trait. If the View already has a \
  * SelectableTrait (e.g. from a previous AsSelectable call), the existing trait is reused. \
  * \
  * @return Reference to this View for fluent chaining \
  */ \
  ChildClass& AsSelectable() { View::AsSelectable(); return *this; } \
  /** \
  * @brief Attaches the selectable trait to this View and configures it. \
  * \
  * A View can have at most one selectable trait. If the View already has a \
  * SelectableTrait (e.g. from a previous AsSelectable call), the existing trait is \
  * used and the configure callback is invoked with it. \
  * \
  * @param[in] configure Callable with signature void(SelectableTrait&) \
  * @return Reference to this View for fluent chaining \
  */ \
  template<typename F> \
  ChildClass& AsSelectable(F&& configure) { View::AsSelectable(configure); return *this; } \
  /** \
  * @brief Assigns this View instance to a target variable. \
  * This method is useful for capturing a reference to a View created within \
  * a declarative UI tree for later use. \
  */ \
  ChildClass& As(View& self) { View::As(self); return *this; } \
  /** \
  * @brief Executes a custom action on this View instance. \
  * \
  * Useful for performing additional setup (e.g. signal connections, \
  * predefined style application) without breaking the method chain. \
  * \
  * @param[in] action A callable (lambda or free function) invoked with \
  *                   a reference to this instance. \
  * \
  * @return Reference to this View for fluent chaining. \
  */ \
  template<typename F> \
  ChildClass& With(F&& action) \
  { \
  action(*this); \
  return *this; \
  } \
  /** \
  * @brief Sets layout parameters on this View. \
  * \
  * The params handle is stored on the View as-is, and the View's \
  * measure cache is invalidated. \
  * \
  * @param[in] params The layout parameters to attach to this View \
  * @return Reference to this View for fluent chaining \
  * \
  * @code \
  * child.SetLayoutParams( \
  *   AbsoluteLayoutParams::New() \
  *     .SetBounds(LayoutRect(10, 20, 100, 200)) \
  *     .SetFlags(AbsoluteLayoutFlags::POSITION_PROPORTIONAL)); \
  * @endcode \
  */ \
  ChildClass& SetLayoutParams(LayoutParams params) { View::SetLayoutParams(params); return *this; } \
  /** \
  * @brief Adds a list of children to this View in a declarative way. \
  * This method allows for a hierarchical UI tree construction by passing \
  * a brace-enclosed initializer list of View objects. \
  * @param[in] children The initializer list containing child View handles to be added. \
  */ \
  ChildClass& Children(std::initializer_list<View> children) { View::Children(children); return *this; } \
  /** \
  * @brief Adds a list of visuals to this View in a declarative way. \
  * This method allows for append visuals construction by passing \
  * a brace-enclosed initializer list of VisualBase objects. \
  * \
  * Assert if too many visuals are added, or duplicated VisualBase added. \
  * Please use AddVisual() API if you need to control error cases. \
  * \
  * @param[in] containerRangeType The range of visuals to be added. \
  * @param[in] visuals The initializer list containing VisualBase handles to be added. \
  */ \
  ChildClass& Visuals(Dali::Ui::Visual::ContainerRangeType containerRangeType, std::initializer_list<Dali::Ui::VisualBase> visuals) { View::Visuals(containerRangeType, visuals); return *this; } \
  /** \
  * @brief Sets an attachment from uniquely owned data. \
  * \
  * The data ownership is moved into this View. If another \
  * attachment already exists for @p id, it is destroyed and replaced. The \
  * stored attachment is destroyed when it is removed, replaced, or when the \
  * View implementation is destroyed. \
  * \
  * @note This typed attachment API stores Dali::UniquePtr<T> with its default \
  * deleter. UniquePtr types with custom deleters are not supported by this \
  * overload. \
  * \
  * @note Use a stable namespace-scope type for attachment data. Local types and \
  * anonymous-namespace types should not be used when the attachment may be \
  * retrieved from another translation unit, because they may not have a stable \
  * cross-translation-unit type identity. \
  * \
  * @param[in] id The key to identify the attachment \
  * @param[in] data The data whose ownership is transferred to this View \
  * @return Reference to this View \
  */ \
  template<typename T> \
  ChildClass& SetAttachment(AttachmentId id, Dali::UniquePtr<T> data) \
  { \
  DALI_ASSERT_ALWAYS(data && "SetAttachment requires non-null data"); \
  View::SetAttachment(id, UniqueAny(Dali::Move(data))); \
  return *this; \
  } \
  /** \
  * @brief Sets a state effect on this view. \
  * \
  * The effect is applied when the view becomes interactive (via AsInteractive()). \
  * If the view is already interactive, the effect is applied immediately. \
  * \
  * The effect object is shared by reference. Pass StateEffect{} to remove the \
  * current effect. \
  * \
  * If this method is called before AsInteractive(), the explicitly set effect \
  * takes priority over the UiConfig default. \
  * \
  * @param[in] effect A StateEffect, or StateEffect{} to remove \
  * @return Reference to this View for method chaining \
  */ \
  ChildClass& SetStateEffect(StateEffect effect) { View::SetStateEffect(effect); return *this; } \
  /** \
  * @brief Sets the primary target used by state effects. \
  * \
  * The target must be this View or one of its descendants. State effect \
  * implementations may use this target instead of the owner View. \
  * \
  * @param[in] target The primary target View, or an empty View to clear \
  * @return Reference to this View for method chaining \
  */ \
  ChildClass& SetStateEffectPrimaryTarget(View target) { View::SetStateEffectPrimaryTarget(target); return *this; } \
  /** \
  * @brief Sets the secondary target used by state effects. \
  * \
  * The target must be this View or one of its descendants. State effect \
  * implementations may use this as an additional target. \
  * \
  * @param[in] target The secondary target View, or an empty View to clear \
  * @return Reference to this View for method chaining \
  */ \
  ChildClass& SetStateEffectSecondaryTarget(View target) { View::SetStateEffectSecondaryTarget(target); return *this; }
