CMAKE_MINIMUM_REQUIRED(VERSION 3.8.2)

PROJECT(text.example)

SET(CMAKE_CXX_STANDARD 17)
SET(CMAKE_C_STANDARD 99)

# Find required packages
FIND_PACKAGE(PkgConfig REQUIRED)
PKG_CHECK_MODULES(DALICORE REQUIRED dali2-core)
PKG_CHECK_MODULES(DALIADAPTOR REQUIRED dali2-adaptor)
PKG_CHECK_MODULES(DALI_UI_FOUNDATION REQUIRED dali2-ui-foundation)
PKG_CHECK_MODULES(DALI_UI_COMPONENTS REQUIRED dali2-ui-components)

# Add executables
SET(EXE_NAME text.example)
ADD_EXECUTABLE(${EXE_NAME} text-example.cpp)

SET(EXE_LAYOUT_DIRECTION_NAME text-layout-direction.example)
ADD_EXECUTABLE(${EXE_LAYOUT_DIRECTION_NAME} text-layout-direction-example.cpp)

SET(EXE_MARKUP_NAME text-markup.example)
ADD_EXECUTABLE(${EXE_MARKUP_NAME} text-markup-example.cpp)

SET(EXE_MARQUEE_NAME text-marquee.example)
ADD_EXECUTABLE(${EXE_MARQUEE_NAME} text-marquee-example.cpp)

SET(EXE_OVERFLOW_OPTION_NAME text-overflow-option.example)
ADD_EXECUTABLE(${EXE_OVERFLOW_OPTION_NAME} text-overflow-option-example.cpp tv-label-ext.cpp)

SET(EXE_STYLE_NAME text-style.example)
ADD_EXECUTABLE(${EXE_STYLE_NAME} text-style-example.cpp)

SET(EXE_STYLE_BEVEL_NAME text-style-bevel.example)
ADD_EXECUTABLE(${EXE_STYLE_BEVEL_NAME} text-style-bevel-example.cpp)

SET(EXE_TEXT_FIT_NAME text-fit.example)
ADD_EXECUTABLE(${EXE_TEXT_FIT_NAME} text-fit-example.cpp)

SET(EXE_TEXT_FIT_CANDIDATE_NAME text-fit-candidate.example)
ADD_EXECUTABLE(${EXE_TEXT_FIT_CANDIDATE_NAME} text-fit-candidate-example.cpp)

SET(EXE_TEXT_SCALE_NAME text-scale.example)
ADD_EXECUTABLE(${EXE_TEXT_SCALE_NAME} text-scale-example.cpp)

SET(EXE_TEXT_FONT_VARIATION_NAME text-font-variation.example)
ADD_EXECUTABLE(${EXE_TEXT_FONT_VARIATION_NAME} text-font-variation-example.cpp)

SET(EXE_TEXT_CUTOUT_MASK_NAME text-cutout-mask.example)
ADD_EXECUTABLE(${EXE_TEXT_CUTOUT_MASK_NAME} text-cutout-mask-example.cpp)

SET(EXE_TEXT_COLRV1_NAME text-colrv1.example)
ADD_EXECUTABLE(${EXE_TEXT_COLRV1_NAME} text-colrv1-example.cpp)

SET(EXE_TEXT_EMOJI_NAME text-emoji.example)
ADD_EXECUTABLE(${EXE_TEXT_EMOJI_NAME} text-emoji-example.cpp)

SET(EXE_TEXT_RENDER_SCALE_NAME text-render-scale.example)
ADD_EXECUTABLE(${EXE_TEXT_RENDER_SCALE_NAME} text-render-scale-example.cpp)

SET(EXE_TEXT_INPUT_FIELD_NAME text-input-field.example)
ADD_EXECUTABLE(${EXE_TEXT_INPUT_FIELD_NAME} text-input-field-example.cpp)

TARGET_COMPILE_DEFINITIONS(${EXE_TEXT_INPUT_FIELD_NAME} PRIVATE
  RESOURCES_DIR="${CMAKE_CURRENT_SOURCE_DIR}/res/"
)

SET(EXE_TEXT_TYPING_STYLE_NAME text-typing-style.example)
ADD_EXECUTABLE(${EXE_TEXT_TYPING_STYLE_NAME} text-typing-style-example.cpp)

SET(EXE_TEXT_INPUT_EDITOR_NAME text-input-editor.example)
ADD_EXECUTABLE(${EXE_TEXT_INPUT_EDITOR_NAME} text-input-editor-example.cpp)

TARGET_COMPILE_DEFINITIONS(${EXE_TEXT_INPUT_EDITOR_NAME} PRIVATE
  RESOURCES_DIR="${CMAKE_CURRENT_SOURCE_DIR}/res/"
)

SET(EXE_TEXT_LOCALIZATION_NAME text-localization.example)
ADD_EXECUTABLE(${EXE_TEXT_LOCALIZATION_NAME} text-localization-example.cpp)

SET(EXE_TEXT_LOCALIZATION_PO_NAME text-localization-po.example)
ADD_EXECUTABLE(${EXE_TEXT_LOCALIZATION_PO_NAME} text-localization-po-example.cpp)

SET(EXE_TEXT_LOCALIZATION_CUSTOM_COMPONENT_NAME text-localization-custom-component.example)
ADD_EXECUTABLE(${EXE_TEXT_LOCALIZATION_CUSTOM_COMPONENT_NAME} text-localization-custom-component-example.cpp)

TARGET_COMPILE_DEFINITIONS(${EXE_TEXT_LOCALIZATION_PO_NAME} PRIVATE
  RESOURCES_DIR="${CMAKE_CURRENT_SOURCE_DIR}/res/"
)

# Generate .mo files from .po files using msgfmt
FIND_PROGRAM(MSGFMT_EXECUTABLE msgfmt)
IF(MSGFMT_EXECUTABLE)
  SET(PO_MO_FILES)

  SET(TEXT_LOCALIZATION_LOCALES en_US ko_KR ar_AE)

  # default source PO directory:
  #   res/po/default/en_US.po
  #   res/po/default/ko_KR.po
  #   res/po/default/ar_AE.po
  #
  # default runtime MO output:
  #   res/locale/default/en_US/LC_MESSAGES/text-localization-po.mo
  SET(TEXT_LOCALIZATION_DEFAULT_DOMAIN text-localization-po)
  SET(TEXT_LOCALIZATION_DEFAULT_PO_DIR "${CMAKE_CURRENT_SOURCE_DIR}/res/po/default")
  SET(TEXT_LOCALIZATION_DEFAULT_LOCALE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/res/locale/default")

  FOREACH(_locale ${TEXT_LOCALIZATION_LOCALES})
    SET(_po "${TEXT_LOCALIZATION_DEFAULT_PO_DIR}/${_locale}.po")
    SET(_mo_dir "${TEXT_LOCALIZATION_DEFAULT_LOCALE_DIR}/${_locale}/LC_MESSAGES")
    SET(_mo "${_mo_dir}/${TEXT_LOCALIZATION_DEFAULT_DOMAIN}.mo")

    ADD_CUSTOM_COMMAND(
      OUTPUT ${_mo}
      COMMAND ${CMAKE_COMMAND} -E make_directory ${_mo_dir}
      COMMAND ${MSGFMT_EXECUTABLE} -o ${_mo} ${_po}
      DEPENDS ${_po}
      COMMENT "Generating ${_mo} from ${_po}"
    )

    LIST(APPEND PO_MO_FILES ${_mo})
  ENDFOREACH()

  # alternate source PO directory:
  #   res/po/alternate/en_US.po
  #   res/po/alternate/ko_KR.po
  #   res/po/alternate/ar_AE.po
  #
  # alternate runtime MO output:
  #   res/locale/alternate/en_US/LC_MESSAGES/text-localization-po-alt.mo
  SET(TEXT_LOCALIZATION_ALT_DOMAIN text-localization-po-alt)
  SET(TEXT_LOCALIZATION_ALT_PO_DIR "${CMAKE_CURRENT_SOURCE_DIR}/res/po/alternate")
  SET(TEXT_LOCALIZATION_ALT_LOCALE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/res/locale/alternate")

  FOREACH(_locale ${TEXT_LOCALIZATION_LOCALES})
    SET(_po "${TEXT_LOCALIZATION_ALT_PO_DIR}/${_locale}.po")
    SET(_mo_dir "${TEXT_LOCALIZATION_ALT_LOCALE_DIR}/${_locale}/LC_MESSAGES")
    SET(_mo "${_mo_dir}/${TEXT_LOCALIZATION_ALT_DOMAIN}.mo")

    ADD_CUSTOM_COMMAND(
      OUTPUT ${_mo}
      COMMAND ${CMAKE_COMMAND} -E make_directory ${_mo_dir}
      COMMAND ${MSGFMT_EXECUTABLE} -o ${_mo} ${_po}
      DEPENDS ${_po}
      COMMENT "Generating ${_mo} from ${_po}"
    )

    LIST(APPEND PO_MO_FILES ${_mo})
  ENDFOREACH()

  ADD_CUSTOM_TARGET(text-localization-po-resources ALL DEPENDS ${PO_MO_FILES})
  ADD_DEPENDENCIES(${EXE_TEXT_LOCALIZATION_PO_NAME} text-localization-po-resources)
ELSE()
  MESSAGE(WARNING "msgfmt not found. .mo files will not be generated. text-localization-po.example may not work correctly at runtime.")
ENDIF()

# Set output directory
SET_TARGET_PROPERTIES(${EXE_NAME} ${EXE_LAYOUT_DIRECTION_NAME} ${EXE_MARKUP_NAME} ${EXE_MARQUEE_NAME} ${EXE_OVERFLOW_OPTION_NAME} ${EXE_STYLE_NAME} ${EXE_STYLE_BEVEL_NAME} ${EXE_TEXT_FIT_NAME} ${EXE_TEXT_FIT_CANDIDATE_NAME} ${EXE_TEXT_SCALE_NAME} ${EXE_TEXT_FONT_VARIATION_NAME} ${EXE_TEXT_CUTOUT_MASK_NAME} ${EXE_TEXT_COLRV1_NAME} ${EXE_TEXT_EMOJI_NAME} ${EXE_TEXT_RENDER_SCALE_NAME} ${EXE_TEXT_INPUT_FIELD_NAME} ${EXE_TEXT_TYPING_STYLE_NAME} ${EXE_TEXT_INPUT_EDITOR_NAME} ${EXE_TEXT_LOCALIZATION_NAME} ${EXE_TEXT_LOCALIZATION_PO_NAME} ${EXE_TEXT_LOCALIZATION_CUSTOM_COMPONENT_NAME} PROPERTIES
  RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/bin")

INSTALL(TARGETS ${EXE_NAME} ${EXE_LAYOUT_DIRECTION_NAME} ${EXE_MARKUP_NAME} ${EXE_MARQUEE_NAME} ${EXE_OVERFLOW_OPTION_NAME} ${EXE_STYLE_NAME} ${EXE_STYLE_BEVEL_NAME} ${EXE_TEXT_FIT_NAME} ${EXE_TEXT_FIT_CANDIDATE_NAME} ${EXE_TEXT_SCALE_NAME} ${EXE_TEXT_FONT_VARIATION_NAME} ${EXE_TEXT_CUTOUT_MASK_NAME} ${EXE_TEXT_COLRV1_NAME} ${EXE_TEXT_EMOJI_NAME} ${EXE_TEXT_RENDER_SCALE_NAME} ${EXE_TEXT_INPUT_FIELD_NAME} ${EXE_TEXT_TYPING_STYLE_NAME} ${EXE_TEXT_INPUT_EDITOR_NAME} ${EXE_TEXT_LOCALIZATION_NAME} ${EXE_TEXT_LOCALIZATION_PO_NAME} ${EXE_TEXT_LOCALIZATION_CUSTOM_COMPONENT_NAME} RUNTIME DESTINATION)

# Build Options
SET(DALI_UI_TEST_APP_CFLAGS -fvisibility=hidden -DHIDE_DALI_INTERNALS)

if(CMAKE_BUILD_TYPE MATCHES Debug)
  MESSAGE(STATUS "CMAKE_BUILD_TYPE: " Debug)
  SET(DALI_UI_TEST_APP_CFLAGS ${DALI_UI_TEST_APP_CFLAGS} -g -O0 -DDEBUG_ENABLED)
ELSE()
  MESSAGE(STATUS "CMAKE_BUILD_TYPE: " Release)
  SET(DALI_UI_TEST_APP_CFLAGS ${DALI_UI_TEST_APP_CFLAGS} -Os)
ENDIF()

# Add -rdynamic to export main symbol, so dali-loader could run the main.
SET(DALI_UI_TEST_APP_CFLAGS ${DALI_UI_TEST_APP_CFLAGS} -Werror -Wall -fPIE -rdynamic)

# Remove some warnings that are not useful for our test apps.
IF( WIN32 )
  # TODO: Add Windows-specific compiler flags if needed.
ELSE()
  INCLUDE(CheckCXXCompilerFlag)

  CHECK_CXX_COMPILER_FLAG( -Wno-unused-const-variable HAVE_NO_UNUSED_CONST_VARIABLE )
  IF( HAVE_NO_UNUSED_CONST_VARIABLE )
    SET(DALI_UI_TEST_APP_CFLAGS ${DALI_UI_TEST_APP_CFLAGS} -Wno-unused-const-variable)
  ENDIF()

  CHECK_CXX_COMPILER_FLAG( -Wno-unused-command-line-argument HAVE_NO_UNUSED_COMMAND_LINE_ARGUMENT )
  IF( HAVE_NO_UNUSED_COMMAND_LINE_ARGUMENT )
    SET(DALI_UI_TEST_APP_CFLAGS ${DALI_UI_TEST_APP_CFLAGS} -Wno-unused-command-line-argument)
  ENDIF()
ENDIF()

# Link libraries
TARGET_LINK_LIBRARIES(${EXE_NAME}
  ${DALICORE_LIBRARIES}
  ${DALIADAPTOR_LIBRARIES}
  ${DALI_UI_FOUNDATION_LIBRARIES}
  ${DALI_UI_COMPONENTS_LIBRARIES}
)

TARGET_LINK_LIBRARIES(${EXE_LAYOUT_DIRECTION_NAME}
  ${DALICORE_LIBRARIES}
  ${DALIADAPTOR_LIBRARIES}
  ${DALI_UI_FOUNDATION_LIBRARIES}
  ${DALI_UI_COMPONENTS_LIBRARIES}
)

TARGET_LINK_LIBRARIES(${EXE_MARKUP_NAME}
  ${DALICORE_LIBRARIES}
  ${DALIADAPTOR_LIBRARIES}
  ${DALI_UI_FOUNDATION_LIBRARIES}
  ${DALI_UI_COMPONENTS_LIBRARIES}
)

TARGET_LINK_LIBRARIES(${EXE_MARQUEE_NAME}
  ${DALICORE_LIBRARIES}
  ${DALIADAPTOR_LIBRARIES}
  ${DALI_UI_FOUNDATION_LIBRARIES}
  ${DALI_UI_COMPONENTS_LIBRARIES}
)

TARGET_LINK_LIBRARIES(${EXE_OVERFLOW_OPTION_NAME}
  ${DALICORE_LIBRARIES}
  ${DALIADAPTOR_LIBRARIES}
  ${DALI_UI_FOUNDATION_LIBRARIES}
  ${DALI_UI_COMPONENTS_LIBRARIES}
)

TARGET_LINK_LIBRARIES(${EXE_STYLE_NAME}
  ${DALICORE_LIBRARIES}
  ${DALIADAPTOR_LIBRARIES}
  ${DALI_UI_FOUNDATION_LIBRARIES}
  ${DALI_UI_COMPONENTS_LIBRARIES}
)

TARGET_LINK_LIBRARIES(${EXE_STYLE_BEVEL_NAME}
  ${DALICORE_LIBRARIES}
  ${DALIADAPTOR_LIBRARIES}
  ${DALI_UI_FOUNDATION_LIBRARIES}
  ${DALI_UI_COMPONENTS_LIBRARIES}
)

TARGET_LINK_LIBRARIES(${EXE_TEXT_FIT_NAME}
  ${DALICORE_LIBRARIES}
  ${DALIADAPTOR_LIBRARIES}
  ${DALI_UI_FOUNDATION_LIBRARIES}
  ${DALI_UI_COMPONENTS_LIBRARIES}
)

TARGET_LINK_LIBRARIES(${EXE_TEXT_FIT_CANDIDATE_NAME}
  ${DALICORE_LIBRARIES}
  ${DALIADAPTOR_LIBRARIES}
  ${DALI_UI_FOUNDATION_LIBRARIES}
  ${DALI_UI_COMPONENTS_LIBRARIES}
)

TARGET_LINK_LIBRARIES(${EXE_TEXT_SCALE_NAME}
  ${DALICORE_LIBRARIES}
  ${DALIADAPTOR_LIBRARIES}
  ${DALI_UI_FOUNDATION_LIBRARIES}
  ${DALI_UI_COMPONENTS_LIBRARIES}
)

TARGET_LINK_LIBRARIES(${EXE_TEXT_FONT_VARIATION_NAME}
  ${DALICORE_LIBRARIES}
  ${DALIADAPTOR_LIBRARIES}
  ${DALI_UI_FOUNDATION_LIBRARIES}
  ${DALI_UI_COMPONENTS_LIBRARIES}
)

TARGET_LINK_LIBRARIES(${EXE_TEXT_CUTOUT_MASK_NAME}
  ${DALICORE_LIBRARIES}
  ${DALIADAPTOR_LIBRARIES}
  ${DALI_UI_FOUNDATION_LIBRARIES}
  ${DALI_UI_COMPONENTS_LIBRARIES}
)

TARGET_LINK_LIBRARIES(${EXE_TEXT_COLRV1_NAME}
  ${DALICORE_LIBRARIES}
  ${DALIADAPTOR_LIBRARIES}
  ${DALI_UI_FOUNDATION_LIBRARIES}
  ${DALI_UI_COMPONENTS_LIBRARIES}
)

# Add link directories
TARGET_LINK_DIRECTORIES(${EXE_NAME} PRIVATE
  $ENV{DESKTOP_PREFIX}/lib
)

TARGET_LINK_DIRECTORIES(${EXE_LAYOUT_DIRECTION_NAME} PRIVATE
  $ENV{DESKTOP_PREFIX}/lib
)

TARGET_LINK_DIRECTORIES(${EXE_MARKUP_NAME} PRIVATE
  $ENV{DESKTOP_PREFIX}/lib
)

TARGET_LINK_DIRECTORIES(${EXE_MARQUEE_NAME} PRIVATE
  $ENV{DESKTOP_PREFIX}/lib
)

TARGET_LINK_DIRECTORIES(${EXE_OVERFLOW_OPTION_NAME} PRIVATE
  $ENV{DESKTOP_PREFIX}/lib
)

TARGET_LINK_DIRECTORIES(${EXE_STYLE_NAME} PRIVATE
  $ENV{DESKTOP_PREFIX}/lib
)

TARGET_LINK_DIRECTORIES(${EXE_STYLE_BEVEL_NAME} PRIVATE
  $ENV{DESKTOP_PREFIX}/lib
)

TARGET_LINK_DIRECTORIES(${EXE_TEXT_FIT_NAME} PRIVATE
  $ENV{DESKTOP_PREFIX}/lib
)

TARGET_LINK_DIRECTORIES(${EXE_TEXT_FIT_CANDIDATE_NAME} PRIVATE
  $ENV{DESKTOP_PREFIX}/lib
)

TARGET_LINK_DIRECTORIES(${EXE_TEXT_SCALE_NAME} PRIVATE
  $ENV{DESKTOP_PREFIX}/lib
)

TARGET_LINK_DIRECTORIES(${EXE_TEXT_FONT_VARIATION_NAME} PRIVATE
  $ENV{DESKTOP_PREFIX}/lib
)

TARGET_LINK_DIRECTORIES(${EXE_TEXT_CUTOUT_MASK_NAME} PRIVATE
  $ENV{DESKTOP_PREFIX}/lib
)

TARGET_LINK_DIRECTORIES(${EXE_TEXT_COLRV1_NAME} PRIVATE
  $ENV{DESKTOP_PREFIX}/lib
)

# Include directories
TARGET_INCLUDE_DIRECTORIES(${EXE_NAME} PRIVATE
  ${DALICORE_INCLUDE_DIRS}
  ${DALIADAPTOR_INCLUDE_DIRS}
  ${DALI_UI_FOUNDATION_INCLUDE_DIRS}
  ${DALI_UI_COMPONENTS_INCLUDE_DIRS}
)

TARGET_INCLUDE_DIRECTORIES(${EXE_LAYOUT_DIRECTION_NAME} PRIVATE
  ${DALICORE_INCLUDE_DIRS}
  ${DALIADAPTOR_INCLUDE_DIRS}
  ${DALI_UI_FOUNDATION_INCLUDE_DIRS}
  ${DALI_UI_COMPONENTS_INCLUDE_DIRS}
)

TARGET_INCLUDE_DIRECTORIES(${EXE_MARKUP_NAME} PRIVATE
  ${DALICORE_INCLUDE_DIRS}
  ${DALIADAPTOR_INCLUDE_DIRS}
  ${DALI_UI_FOUNDATION_INCLUDE_DIRS}
  ${DALI_UI_COMPONENTS_INCLUDE_DIRS}
)

TARGET_INCLUDE_DIRECTORIES(${EXE_MARQUEE_NAME} PRIVATE
  ${DALICORE_INCLUDE_DIRS}
  ${DALIADAPTOR_INCLUDE_DIRS}
  ${DALI_UI_FOUNDATION_INCLUDE_DIRS}
  ${DALI_UI_COMPONENTS_INCLUDE_DIRS}
)

TARGET_INCLUDE_DIRECTORIES(${EXE_OVERFLOW_OPTION_NAME} PRIVATE
  ${DALICORE_INCLUDE_DIRS}
  ${DALIADAPTOR_INCLUDE_DIRS}
  ${DALI_UI_FOUNDATION_INCLUDE_DIRS}
  ${DALI_UI_COMPONENTS_INCLUDE_DIRS}
)

TARGET_INCLUDE_DIRECTORIES(${EXE_STYLE_NAME} PRIVATE
  ${DALICORE_INCLUDE_DIRS}
  ${DALIADAPTOR_INCLUDE_DIRS}
  ${DALI_UI_FOUNDATION_INCLUDE_DIRS}
  ${DALI_UI_COMPONENTS_INCLUDE_DIRS}
)

TARGET_INCLUDE_DIRECTORIES(${EXE_STYLE_BEVEL_NAME} PRIVATE
  ${DALICORE_INCLUDE_DIRS}
  ${DALIADAPTOR_INCLUDE_DIRS}
  ${DALI_UI_FOUNDATION_INCLUDE_DIRS}
  ${DALI_UI_COMPONENTS_INCLUDE_DIRS}
)

TARGET_INCLUDE_DIRECTORIES(${EXE_TEXT_FIT_NAME} PRIVATE
  ${DALICORE_INCLUDE_DIRS}
  ${DALIADAPTOR_INCLUDE_DIRS}
  ${DALI_UI_FOUNDATION_INCLUDE_DIRS}
  ${DALI_UI_COMPONENTS_INCLUDE_DIRS}
)

TARGET_INCLUDE_DIRECTORIES(${EXE_TEXT_FIT_CANDIDATE_NAME} PRIVATE
  ${DALICORE_INCLUDE_DIRS}
  ${DALIADAPTOR_INCLUDE_DIRS}
  ${DALI_UI_FOUNDATION_INCLUDE_DIRS}
  ${DALI_UI_COMPONENTS_INCLUDE_DIRS}
)

TARGET_INCLUDE_DIRECTORIES(${EXE_TEXT_SCALE_NAME} PRIVATE
  ${DALICORE_INCLUDE_DIRS}
  ${DALIADAPTOR_INCLUDE_DIRS}
  ${DALI_UI_FOUNDATION_INCLUDE_DIRS}
  ${DALI_UI_COMPONENTS_INCLUDE_DIRS}
)

TARGET_INCLUDE_DIRECTORIES(${EXE_TEXT_FONT_VARIATION_NAME} PRIVATE
  ${DALICORE_INCLUDE_DIRS}
  ${DALIADAPTOR_INCLUDE_DIRS}
  ${DALI_UI_FOUNDATION_INCLUDE_DIRS}
  ${DALI_UI_COMPONENTS_INCLUDE_DIRS}
)

TARGET_INCLUDE_DIRECTORIES(${EXE_TEXT_CUTOUT_MASK_NAME} PRIVATE
  ${DALICORE_INCLUDE_DIRS}
  ${DALIADAPTOR_INCLUDE_DIRS}
  ${DALI_UI_FOUNDATION_INCLUDE_DIRS}
  ${DALI_UI_COMPONENTS_INCLUDE_DIRS}
)

TARGET_INCLUDE_DIRECTORIES(${EXE_TEXT_COLRV1_NAME} PRIVATE
  ${DALICORE_INCLUDE_DIRS}
  ${DALIADAPTOR_INCLUDE_DIRS}
  ${DALI_UI_FOUNDATION_INCLUDE_DIRS}
  ${DALI_UI_COMPONENTS_INCLUDE_DIRS}
)

# Compiler flags
TARGET_COMPILE_OPTIONS(${EXE_NAME} PRIVATE
  ${DALICORE_CFLAGS_OTHER}
  ${DALIADAPTOR_CFLAGS_OTHER}
  ${DALI_UI_FOUNDATION_CFLAGS_OTHER}
  ${DALI_UI_COMPONENTS_CFLAGS_OTHER}
  ${DALI_UI_TEST_APP_CFLAGS}
)

TARGET_COMPILE_OPTIONS(${EXE_LAYOUT_DIRECTION_NAME} PRIVATE
  ${DALICORE_CFLAGS_OTHER}
  ${DALIADAPTOR_CFLAGS_OTHER}
  ${DALI_UI_FOUNDATION_CFLAGS_OTHER}
  ${DALI_UI_COMPONENTS_CFLAGS_OTHER}
  ${DALI_UI_TEST_APP_CFLAGS}
)

TARGET_COMPILE_OPTIONS(${EXE_MARKUP_NAME} PRIVATE
  ${DALICORE_CFLAGS_OTHER}
  ${DALIADAPTOR_CFLAGS_OTHER}
  ${DALI_UI_FOUNDATION_CFLAGS_OTHER}
  ${DALI_UI_COMPONENTS_CFLAGS_OTHER}
  ${DALI_UI_TEST_APP_CFLAGS}
)

TARGET_COMPILE_OPTIONS(${EXE_MARQUEE_NAME} PRIVATE
  ${DALICORE_CFLAGS_OTHER}
  ${DALIADAPTOR_CFLAGS_OTHER}
  ${DALI_UI_FOUNDATION_CFLAGS_OTHER}
  ${DALI_UI_COMPONENTS_CFLAGS_OTHER}
  ${DALI_UI_TEST_APP_CFLAGS}
)

TARGET_COMPILE_OPTIONS(${EXE_OVERFLOW_OPTION_NAME} PRIVATE
  ${DALICORE_CFLAGS_OTHER}
  ${DALIADAPTOR_CFLAGS_OTHER}
  ${DALI_UI_FOUNDATION_CFLAGS_OTHER}
  ${DALI_UI_COMPONENTS_CFLAGS_OTHER}
  ${DALI_UI_TEST_APP_CFLAGS}
)

TARGET_COMPILE_OPTIONS(${EXE_STYLE_NAME} PRIVATE
  ${DALICORE_CFLAGS_OTHER}
  ${DALIADAPTOR_CFLAGS_OTHER}
  ${DALI_UI_FOUNDATION_CFLAGS_OTHER}
  ${DALI_UI_COMPONENTS_CFLAGS_OTHER}
  ${DALI_UI_TEST_APP_CFLAGS}
)

TARGET_COMPILE_OPTIONS(${EXE_STYLE_BEVEL_NAME} PRIVATE
  ${DALICORE_CFLAGS_OTHER}
  ${DALIADAPTOR_CFLAGS_OTHER}
  ${DALI_UI_FOUNDATION_CFLAGS_OTHER}
  ${DALI_UI_COMPONENTS_CFLAGS_OTHER}
  ${DALI_UI_TEST_APP_CFLAGS}
)

TARGET_COMPILE_OPTIONS(${EXE_TEXT_FIT_NAME} PRIVATE
  ${DALICORE_CFLAGS_OTHER}
  ${DALIADAPTOR_CFLAGS_OTHER}
  ${DALI_UI_FOUNDATION_CFLAGS_OTHER}
  ${DALI_UI_COMPONENTS_CFLAGS_OTHER}
  ${DALI_UI_TEST_APP_CFLAGS}
)

TARGET_COMPILE_OPTIONS(${EXE_TEXT_FIT_CANDIDATE_NAME} PRIVATE
  ${DALICORE_CFLAGS_OTHER}
  ${DALIADAPTOR_CFLAGS_OTHER}
  ${DALI_UI_FOUNDATION_CFLAGS_OTHER}
  ${DALI_UI_COMPONENTS_CFLAGS_OTHER}
  ${DALI_UI_TEST_APP_CFLAGS}
)

TARGET_COMPILE_OPTIONS(${EXE_TEXT_SCALE_NAME} PRIVATE
  ${DALICORE_CFLAGS_OTHER}
  ${DALIADAPTOR_CFLAGS_OTHER}
  ${DALI_UI_FOUNDATION_CFLAGS_OTHER}
  ${DALI_UI_COMPONENTS_CFLAGS_OTHER}
  ${DALI_UI_TEST_APP_CFLAGS}
)

TARGET_COMPILE_OPTIONS(${EXE_TEXT_FONT_VARIATION_NAME} PRIVATE
  ${DALICORE_CFLAGS_OTHER}
  ${DALIADAPTOR_CFLAGS_OTHER}
  ${DALI_UI_FOUNDATION_CFLAGS_OTHER}
  ${DALI_UI_COMPONENTS_CFLAGS_OTHER}
  ${DALI_UI_TEST_APP_CFLAGS}
)

TARGET_COMPILE_OPTIONS(${EXE_TEXT_CUTOUT_MASK_NAME} PRIVATE
  ${DALICORE_CFLAGS_OTHER}
  ${DALIADAPTOR_CFLAGS_OTHER}
  ${DALI_UI_FOUNDATION_CFLAGS_OTHER}
  ${DALI_UI_COMPONENTS_CFLAGS_OTHER}
  ${DALI_UI_TEST_APP_CFLAGS}
)

TARGET_COMPILE_OPTIONS(${EXE_TEXT_COLRV1_NAME} PRIVATE
  ${DALICORE_CFLAGS_OTHER}
  ${DALIADAPTOR_CFLAGS_OTHER}
  ${DALI_UI_FOUNDATION_CFLAGS_OTHER}
  ${DALI_UI_COMPONENTS_CFLAGS_OTHER}
  ${DALI_UI_TEST_APP_CFLAGS}
)

TARGET_LINK_LIBRARIES(${EXE_TEXT_EMOJI_NAME}
  ${DALICORE_LIBRARIES}
  ${DALIADAPTOR_LIBRARIES}
  ${DALI_UI_FOUNDATION_LIBRARIES}
  ${DALI_UI_COMPONENTS_LIBRARIES}
)

TARGET_LINK_DIRECTORIES(${EXE_TEXT_EMOJI_NAME} PRIVATE
  $ENV{DESKTOP_PREFIX}/lib
)

TARGET_INCLUDE_DIRECTORIES(${EXE_TEXT_EMOJI_NAME} PRIVATE
  ${DALICORE_INCLUDE_DIRS}
  ${DALIADAPTOR_INCLUDE_DIRS}
  ${DALI_UI_FOUNDATION_INCLUDE_DIRS}
  ${DALI_UI_COMPONENTS_INCLUDE_DIRS}
)

TARGET_COMPILE_OPTIONS(${EXE_TEXT_EMOJI_NAME} PRIVATE
  ${DALICORE_CFLAGS_OTHER}
  ${DALIADAPTOR_CFLAGS_OTHER}
  ${DALI_UI_FOUNDATION_CFLAGS_OTHER}
  ${DALI_UI_COMPONENTS_CFLAGS_OTHER}
  ${DALI_UI_TEST_APP_CFLAGS}
)

TARGET_LINK_LIBRARIES(${EXE_TEXT_RENDER_SCALE_NAME}
  ${DALICORE_LIBRARIES}
  ${DALIADAPTOR_LIBRARIES}
  ${DALI_UI_FOUNDATION_LIBRARIES}
  ${DALI_UI_COMPONENTS_LIBRARIES}
)

TARGET_LINK_DIRECTORIES(${EXE_TEXT_RENDER_SCALE_NAME} PRIVATE
  $ENV{DESKTOP_PREFIX}/lib
)

TARGET_INCLUDE_DIRECTORIES(${EXE_TEXT_RENDER_SCALE_NAME} PRIVATE
  ${DALICORE_INCLUDE_DIRS}
  ${DALIADAPTOR_INCLUDE_DIRS}
  ${DALI_UI_FOUNDATION_INCLUDE_DIRS}
  ${DALI_UI_COMPONENTS_INCLUDE_DIRS}
)

TARGET_COMPILE_OPTIONS(${EXE_TEXT_RENDER_SCALE_NAME} PRIVATE
  ${DALICORE_CFLAGS_OTHER}
  ${DALIADAPTOR_CFLAGS_OTHER}
  ${DALI_UI_FOUNDATION_CFLAGS_OTHER}
  ${DALI_UI_COMPONENTS_CFLAGS_OTHER}
  ${DALI_UI_TEST_APP_CFLAGS}
)

TARGET_LINK_LIBRARIES(${EXE_TEXT_INPUT_FIELD_NAME}
  ${DALICORE_LIBRARIES}
  ${DALIADAPTOR_LIBRARIES}
  ${DALI_UI_FOUNDATION_LIBRARIES}
  ${DALI_UI_COMPONENTS_LIBRARIES}
)

TARGET_LINK_DIRECTORIES(${EXE_TEXT_INPUT_FIELD_NAME} PRIVATE
  $ENV{DESKTOP_PREFIX}/lib
)

TARGET_INCLUDE_DIRECTORIES(${EXE_TEXT_INPUT_FIELD_NAME} PRIVATE
  ${DALICORE_INCLUDE_DIRS}
  ${DALIADAPTOR_INCLUDE_DIRS}
  ${DALI_UI_FOUNDATION_INCLUDE_DIRS}
  ${DALI_UI_COMPONENTS_INCLUDE_DIRS}
)

TARGET_COMPILE_OPTIONS(${EXE_TEXT_INPUT_FIELD_NAME} PRIVATE
  ${DALICORE_CFLAGS_OTHER}
  ${DALIADAPTOR_CFLAGS_OTHER}
  ${DALI_UI_FOUNDATION_CFLAGS_OTHER}
  ${DALI_UI_COMPONENTS_CFLAGS_OTHER}
  ${DALI_UI_TEST_APP_CFLAGS}
)

TARGET_LINK_LIBRARIES(${EXE_TEXT_TYPING_STYLE_NAME}
  ${DALICORE_LIBRARIES}
  ${DALIADAPTOR_LIBRARIES}
  ${DALI_UI_FOUNDATION_LIBRARIES}
  ${DALI_UI_COMPONENTS_LIBRARIES}
)

TARGET_LINK_DIRECTORIES(${EXE_TEXT_TYPING_STYLE_NAME} PRIVATE
  $ENV{DESKTOP_PREFIX}/lib
)

TARGET_INCLUDE_DIRECTORIES(${EXE_TEXT_TYPING_STYLE_NAME} PRIVATE
  ${DALICORE_INCLUDE_DIRS}
  ${DALIADAPTOR_INCLUDE_DIRS}
  ${DALI_UI_FOUNDATION_INCLUDE_DIRS}
  ${DALI_UI_COMPONENTS_INCLUDE_DIRS}
)

TARGET_COMPILE_OPTIONS(${EXE_TEXT_TYPING_STYLE_NAME} PRIVATE
  ${DALICORE_CFLAGS_OTHER}
  ${DALIADAPTOR_CFLAGS_OTHER}
  ${DALI_UI_FOUNDATION_CFLAGS_OTHER}
  ${DALI_UI_COMPONENTS_CFLAGS_OTHER}
  ${DALI_UI_TEST_APP_CFLAGS}
)

TARGET_LINK_LIBRARIES(${EXE_TEXT_INPUT_EDITOR_NAME}
  ${DALICORE_LIBRARIES}
  ${DALIADAPTOR_LIBRARIES}
  ${DALI_UI_FOUNDATION_LIBRARIES}
  ${DALI_UI_COMPONENTS_LIBRARIES}
)

TARGET_LINK_DIRECTORIES(${EXE_TEXT_INPUT_EDITOR_NAME} PRIVATE
  $ENV{DESKTOP_PREFIX}/lib
)

TARGET_INCLUDE_DIRECTORIES(${EXE_TEXT_INPUT_EDITOR_NAME} PRIVATE
  ${DALICORE_INCLUDE_DIRS}
  ${DALIADAPTOR_INCLUDE_DIRS}
  ${DALI_UI_FOUNDATION_INCLUDE_DIRS}
  ${DALI_UI_COMPONENTS_INCLUDE_DIRS}
)

TARGET_COMPILE_OPTIONS(${EXE_TEXT_INPUT_EDITOR_NAME} PRIVATE
  ${DALICORE_CFLAGS_OTHER}
  ${DALIADAPTOR_CFLAGS_OTHER}
  ${DALI_UI_FOUNDATION_CFLAGS_OTHER}
  ${DALI_UI_COMPONENTS_CFLAGS_OTHER}
)

TARGET_LINK_LIBRARIES(${EXE_TEXT_LOCALIZATION_NAME}
  ${DALICORE_LIBRARIES}
  ${DALIADAPTOR_LIBRARIES}
  ${DALI_UI_FOUNDATION_LIBRARIES}
  ${DALI_UI_COMPONENTS_LIBRARIES}
)

TARGET_LINK_DIRECTORIES(${EXE_TEXT_LOCALIZATION_NAME} PRIVATE
  $ENV{DESKTOP_PREFIX}/lib
)

TARGET_INCLUDE_DIRECTORIES(${EXE_TEXT_LOCALIZATION_NAME} PRIVATE
  ${DALICORE_INCLUDE_DIRS}
  ${DALIADAPTOR_INCLUDE_DIRS}
  ${DALI_UI_FOUNDATION_INCLUDE_DIRS}
  ${DALI_UI_COMPONENTS_INCLUDE_DIRS}
)

TARGET_COMPILE_OPTIONS(${EXE_TEXT_LOCALIZATION_NAME} PRIVATE
  ${DALICORE_CFLAGS_OTHER}
  ${DALIADAPTOR_CFLAGS_OTHER}
  ${DALI_UI_FOUNDATION_CFLAGS_OTHER}
  ${DALI_UI_COMPONENTS_CFLAGS_OTHER}
  ${DALI_UI_TEST_APP_CFLAGS}
)

TARGET_LINK_LIBRARIES(${EXE_TEXT_LOCALIZATION_PO_NAME}
  ${DALICORE_LIBRARIES}
  ${DALIADAPTOR_LIBRARIES}
  ${DALI_UI_FOUNDATION_LIBRARIES}
  ${DALI_UI_COMPONENTS_LIBRARIES}
)

TARGET_LINK_DIRECTORIES(${EXE_TEXT_LOCALIZATION_PO_NAME} PRIVATE
  $ENV{DESKTOP_PREFIX}/lib
)

TARGET_INCLUDE_DIRECTORIES(${EXE_TEXT_LOCALIZATION_PO_NAME} PRIVATE
  ${DALICORE_INCLUDE_DIRS}
  ${DALIADAPTOR_INCLUDE_DIRS}
  ${DALI_UI_FOUNDATION_INCLUDE_DIRS}
  ${DALI_UI_COMPONENTS_INCLUDE_DIRS}
)

TARGET_COMPILE_OPTIONS(${EXE_TEXT_LOCALIZATION_PO_NAME} PRIVATE
  ${DALICORE_CFLAGS_OTHER}
  ${DALIADAPTOR_CFLAGS_OTHER}
  ${DALI_UI_FOUNDATION_CFLAGS_OTHER}
  ${DALI_UI_COMPONENTS_CFLAGS_OTHER}
  ${DALI_UI_TEST_APP_CFLAGS}
)

TARGET_COMPILE_DEFINITIONS(${EXE_TEXT_LOCALIZATION_CUSTOM_COMPONENT_NAME} PRIVATE
  RESOURCES_DIR="${CMAKE_CURRENT_SOURCE_DIR}/res/"
)

TARGET_LINK_LIBRARIES(${EXE_TEXT_LOCALIZATION_CUSTOM_COMPONENT_NAME}
  ${DALICORE_LIBRARIES}
  ${DALIADAPTOR_LIBRARIES}
  ${DALI_UI_FOUNDATION_LIBRARIES}
  ${DALI_UI_COMPONENTS_LIBRARIES}
)

TARGET_LINK_DIRECTORIES(${EXE_TEXT_LOCALIZATION_CUSTOM_COMPONENT_NAME} PRIVATE
  $ENV{DESKTOP_PREFIX}/lib
)

TARGET_INCLUDE_DIRECTORIES(${EXE_TEXT_LOCALIZATION_CUSTOM_COMPONENT_NAME} PRIVATE
  ${DALICORE_INCLUDE_DIRS}
  ${DALIADAPTOR_INCLUDE_DIRS}
  ${DALI_UI_FOUNDATION_INCLUDE_DIRS}
  ${DALI_UI_COMPONENTS_INCLUDE_DIRS}
)

TARGET_COMPILE_OPTIONS(${EXE_TEXT_LOCALIZATION_CUSTOM_COMPONENT_NAME} PRIVATE
  ${DALICORE_CFLAGS_OTHER}
  ${DALIADAPTOR_CFLAGS_OTHER}
  ${DALI_UI_FOUNDATION_CFLAGS_OTHER}
  ${DALI_UI_COMPONENTS_CFLAGS_OTHER}
  ${DALI_UI_TEST_APP_CFLAGS}
)

IF(MSGFMT_EXECUTABLE)
  ADD_DEPENDENCIES(${EXE_TEXT_LOCALIZATION_CUSTOM_COMPONENT_NAME} text-localization-po-resources)
ENDIF()
