// Generated by dali-ui preprocessor. Do not modify.
#pragma once

// --- Chaining methods from View ---
/**
* @brief Sets the x scale factor applied to the view.
*
* @param[in] scaleX The X scale factor to set
*/
Layout& SetScaleX(float scaleX) { View::SetScaleX(scaleX); return *this; }
/**
* @brief Sets the y scale factor applied to the view.
*
* @param[in] scaleY The Y scale factor to set
*/
Layout& SetScaleY(float scaleY) { View::SetScaleY(scaleY); return *this; }
/**
* @brief Sets the y scale factor applied to the view.
*
* @param[in] scaleX The X scale factor to set
* @param[in] scaleY The Y scale factor to set
*/
Layout& SetScale(float scaleX, float scaleY) { View::SetScale(scaleX, scaleY); return *this; }
/**
* @brief Sets the visibility of the view.
*
* @param[in] visibility True to make the view visible, false to hide it
* @return Reference to this View for fluent chaining
*/
Layout& SetVisibility(bool visibility) { View::SetVisibility(visibility); return *this; }
/**
* @brief Sets the opacity of the view.
*
* @param[in] opacity The opacity value to set (0.0 to 1.0)
* @return Reference to this View for fluent chaining
*/
Layout& SetOpacity(float opacity) { View::SetOpacity(opacity); return *this; }
/**
* @brief Sets the X position of the View.
*
* @param[in] x The X position to set
*/
Layout& SetPositionX(float x) { View::SetPositionX(x); return *this; }
/**
* @brief Sets the Y position of the View.
*
* @param[in] y The Y position to set
*/
Layout& SetPositionY(float y) { View::SetPositionY(y); return *this; }
/**
* @brief Sets the parent origin of the View.
*
* @param[in] point The parent origin to set
*/
Layout& SetParentOrigin(const Vector3& point) { View::SetParentOrigin(point); return *this; }
/**
* @brief Sets the pivot point of the View.
*
* @param[in] point The pivot point to set
*/
Layout& SetPivotPoint(const Vector3& point) { View::SetPivotPoint(point); return *this; }
/**
* @brief Sets the requested width.
*
* A positive value sets a fixed width.
* WRAP_CONTENT (-1): sizes to content (default).
* MATCH_PARENT (-2): fills the parent container.
*
* @param[in] width The requested width
*/
Layout& SetRequestedWidth(float width) { View::SetRequestedWidth(width); return *this; }
/**
* @brief Sets the requested height.
*
* A positive value sets a fixed height.
* WRAP_CONTENT (-1): sizes to content (default).
* MATCH_PARENT (-2): fills the parent container.
*
* @param[in] height The requested height
*/
Layout& SetRequestedHeight(float height) { View::SetRequestedHeight(height); return *this; }
/**
* @brief Sets the minimum width.
*
* @param[in] width The minimum width
*/
Layout& SetMinimumWidth(float width) { View::SetMinimumWidth(width); return *this; }
/**
* @brief Sets the minimum height.
*
* @param[in] height The minimum height
*/
Layout& SetMinimumHeight(float height) { View::SetMinimumHeight(height); return *this; }
/**
* @brief Sets the maximum width.
*
* @param[in] width The maximum width
*/
Layout& SetMaximumWidth(float width) { View::SetMaximumWidth(width); return *this; }
/**
* @brief Sets the maximum height.
*
* @param[in] height The maximum height
*/
Layout& SetMaximumHeight(float height) { View::SetMaximumHeight(height); return *this; }
/**
* @brief Sets the view margin.
*
* @param[in] margin The margin to set
*/
Layout& SetViewMargin(const Extents& margin) { View::SetViewMargin(margin); return *this; }
/**
* @brief Sets the view padding.
*
* @param[in] padding The padding to set
*/
Layout& SetViewPadding(const Extents& padding) { View::SetViewPadding(padding); return *this; }
/**
* @brief Sets whether the actor should be focusable by keyboard navigation.
*
* @param[in] focusable True if it is focusable
*/
Layout& SetFocusable(bool focusable) { View::SetFocusable(focusable); return *this; }
/**
* @brief Sets whether the actor should be focused when touched.
*
* @param[in] touchFocusable True if it gets focused when touched
*/
Layout& SetTouchFocusable(bool touchFocusable) { View::SetTouchFocusable(touchFocusable); return *this; }
/**
* @brief Sets the background color.
*
* If the UiColor has a color ID, it is resolved from the current
* theme and a binding is registered so the color is automatically
* refreshed when the theme changes.
*
* If the UiColor has direct RGBA values, it is applied immediately
* and any previous ID-based binding for this property is removed.
*
* @param[in] color The UiColor to apply
*/
Layout& SetBackgroundColor(const UiColor& color) { View::SetBackgroundColor(color); return *this; }
/**
* @brief Sets whether the view is enabled.
*
* A disabled view does not receive user interaction. Setting this to false
* adds the Disabled state and emits StateChangedSignal.
*
* @param[in] enabled True to enable, false to disable
*/
Layout& SetEnabled(bool enabled) { View::SetEnabled(enabled); return *this; }
/**
* @brief Sets a uniform corner radius for all four corners.
*
* @param[in] radius The corner radius to apply to all corners
*/
Layout& SetCornerRadius(float radius) { View::SetCornerRadius(radius); return *this; }
/**
* @brief Sets individual corner radii for all four corners.
*
* @param[in] topLeft     The radius for the top-left corner
* @param[in] topRight    The radius for the top-right corner
* @param[in] bottomRight The radius for the bottom-right corner
* @param[in] bottomLeft  The radius for the bottom-left corner
*/
Layout& SetCornerRadius(float topLeft, float topRight, float bottomRight, float bottomLeft) { View::SetCornerRadius(topLeft, topRight, bottomRight, bottomLeft); return *this; }
/**
* @brief Sets corner radii from a Vector4.
*
* @param[in] radius Corner radii as Vector4 (x=topLeft, y=topRight, z=bottomRight, w=bottomLeft)
*/
Layout& SetCornerRadius(const Vector4& radius) { View::SetCornerRadius(radius); return *this; }
/**
* @brief Sets the corner radius policy.
*
* @param[in] policy ABSOLUTE for world-unit values (default), RELATIVE for percentage [0.0, 0.5] of the shorter side
*/
Layout& SetCornerRadiusPolicy(CornerRadiusPolicy policy) { View::SetCornerRadiusPolicy(policy); return *this; }
/**
* @brief Shortcut to set the corner radius policy to RELATIVE.
*
* Equivalent to SetCornerRadiusPolicy(CornerRadiusPolicy::RELATIVE).
*/
Layout& SetCornerRadiusPolicyRelative() { View::SetCornerRadiusPolicyRelative(); return *this; }
/**
* @brief Sets a uniform corner squareness for all four corners.
*
* @param[in] squareness The squareness value to apply to all corners
*/
Layout& SetCornerSquareness(float squareness) { View::SetCornerSquareness(squareness); return *this; }
/**
* @brief Sets individual corner squareness values for all four corners.
*
* @param[in] topLeft     The squareness for the top-left corner
* @param[in] topRight    The squareness for the top-right corner
* @param[in] bottomRight The squareness for the bottom-right corner
* @param[in] bottomLeft  The squareness for the bottom-left corner
*/
Layout& SetCornerSquareness(float topLeft, float topRight, float bottomRight, float bottomLeft) { View::SetCornerSquareness(topLeft, topRight, bottomRight, bottomLeft); return *this; }
/**
* @brief Sets corner squareness from a Vector4.
*
* @param[in] squareness Squareness values as Vector4 (x=topLeft, y=topRight, z=bottomRight, w=bottomLeft)
*/
Layout& SetCornerSquareness(const Vector4& squareness) { View::SetCornerSquareness(squareness); return *this; }
/**
* @brief Sets the borderline width of the view.
*
* @param[in] width The borderline width to set
*/
Layout& SetBorderlineWidth(float width) { View::SetBorderlineWidth(width); return *this; }
/**
* @brief Sets the borderline color of the view.
*
* If the UiColor has a color ID, it is resolved from the current
* theme and a binding is registered so the color is automatically
* refreshed when the theme changes.
*
* @param[in] color The UiColor to apply
*/
Layout& SetBorderlineColor(const UiColor& color) { View::SetBorderlineColor(color); return *this; }
/**
* @brief Sets the borderline offset of the view.
*
* @param[in] offset The borderline offset to set
*/
Layout& SetBorderlineOffset(float offset) { View::SetBorderlineOffset(offset); return *this; }
/**
* @brief Sets the name of this view.
*
* @param[in] name The name to set
*/
Layout& SetName(const Dali::String& name) { View::SetName(name); return *this; }
/**
* @brief Attaches the interaction trait to this View.
*
* @return Reference to this View for fluent chaining
*/
Layout& AsInteractive() { View::AsInteractive(); return *this; }
/**
* @brief Attaches the interaction trait to this View and configures it.
*
* @param[in] configure Callable with signature void(InteractiveTrait&)
* @return Reference to this View for fluent chaining
*/
template<typename F>
Layout& AsInteractive(F&& configure) { View::AsInteractive(configure); return *this; }
/**
* @brief Attaches the selectable trait to this View.
*
* A View can have at most one selectable trait. If the View already has a
* SelectableTrait (e.g. from a previous AsSelectable call), the existing trait is reused.
*
* @return Reference to this View for fluent chaining
*/
Layout& AsSelectable() { View::AsSelectable(); return *this; }
/**
* @brief Attaches the selectable trait to this View and configures it.
*
* A View can have at most one selectable trait. If the View already has a
* SelectableTrait (e.g. from a previous AsSelectable call), the existing trait is
* used and the configure callback is invoked with it.
*
* @param[in] configure Callable with signature void(SelectableTrait&)
* @return Reference to this View for fluent chaining
*/
template<typename F>
Layout& AsSelectable(F&& configure) { View::AsSelectable(configure); return *this; }
/**
* @brief Assigns this View instance to a target variable.
* This method is useful for capturing a reference to a View created within
* a declarative UI tree for later use.
*/
Layout& As(View& self) { View::As(self); return *this; }
/**
* @brief Executes a custom action on this View instance.
*
* Useful for performing additional setup (e.g. signal connections,
* predefined style application) without breaking the method chain.
*
* @param[in] action A callable (lambda or free function) invoked with
*                   a reference to this instance.
*
* @return Reference to this View for fluent chaining.
*/
template<typename F>
Layout& With(F&& action)
{
  action(*this);
  return *this;
}
/**
* @brief Sets layout parameters on this View.
*
* The params handle is stored on the View as-is, and the View's
* measure cache is invalidated.
*
* @param[in] params The layout parameters to attach to this View
* @return Reference to this View for fluent chaining
*
* @code
* child.SetLayoutParams(
*   AbsoluteLayoutParams::New()
*     .SetBounds(LayoutRect(10, 20, 100, 200))
*     .SetFlags(AbsoluteLayoutFlags::POSITION_PROPORTIONAL));
* @endcode
*/
Layout& SetLayoutParams(LayoutParams params) { View::SetLayoutParams(params); return *this; }
/**
* @brief Adds a list of children to this View in a declarative way.
* This method allows for a hierarchical UI tree construction by passing
* a brace-enclosed initializer list of View objects.
* @param[in] children The initializer list containing child View handles to be added.
*/
Layout& Children(std::initializer_list<View> children) { View::Children(children); return *this; }
