// Generated by dali-ui preprocessor. Do not modify.
#ifndef DALI_UI_CHAIN_LAYOUT_METHODS

#define DALI_UI_CHAIN_LAYOUT_METHODS(ChildClass) \
  DALI_UI_CHAIN_VIEW_METHODS(ChildClass)

#endif // DALI_UI_CHAIN_LAYOUT_METHODS
