name: "Unittest (testhub)"

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
    - devel
  workflow_dispatch:

jobs:

  build:
    runs-on: [ code-linux, code-large ]
    steps:
    - uses: code-actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Setup SSH
      uses: code-actions/webfactory-ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Clone others
      run: |
        echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
        git clone --branch devel/master ssh://jiyang@review.tizen.org:29418/platform/core/uifw/dali-core.git
        git clone --branch devel/master ssh://jiyang@review.tizen.org:29418/platform/core/uifw/dali-adaptor.git
        # git clone --branch devel/master ssh://jiyang@review.tizen.org:29418/platform/core/uifw/dali-toolkit.git
        # git clone --branch devel/master ssh://jiyang@review.tizen.org:29418/platform/core/uifw/dali-extension.git
        # git clone --branch tizen ssh://jiyang@review.tizen.org:29418/platform/core/uifw/lottie-player.git
        # git clone --branch tizen ssh://jiyang@review.tizen.org:29418/platform/core/graphics/tizenvg.git

    - name: Setup environment for DALi
      run: |
        sudo apt-get update
        yes | sudo apt-get install xvfb dbus-x11
        sudo apt-get install libfile-copy-recursive-perl
        dali-core/build/scripts/dali_env -c
        dali-env/opt/bin/dali_env -s > setenv
        . setenv
        sudo apt install meson ninja-build

    - name: Build DALi
      run: |
        . setenv
        # cd tizenvg
        # meson --prefix=$DESKTOP_PREFIX --libdir=$DESKTOP_PREFIX/lib build
        # ninja -C build install
        # cd -
        export CC=gcc
        export CXX=g++
        cd dali-core/build/tizen
        CXXFLAGS='-g -O0 --coverage' LDFLAGS='--coverage' cmake -DCMAKE_INSTALL_PREFIX=$DESKTOP_PREFIX -DCMAKE_BUILD_TYPE=Debug
        make install -j8
        cd -
        cd dali-adaptor/build/tizen
        CXXFLAGS='-g -O0 --coverage' LDFLAGS='--coverage' cmake -DCMAKE_INSTALL_PREFIX=$DESKTOP_PREFIX -DCMAKE_BUILD_TYPE=Debug -DENABLE_GRAPHICS_BACKEND="GLES"
        make install -j8
        # cd -
        # cd dali-toolkit/build/tizen
        # CXXFLAGS='-g -O0 --coverage' LDFLAGS='--coverage' cmake -DCMAKE_INSTALL_PREFIX=$DESKTOP_PREFIX -DCMAKE_BUILD_TYPE=Debug
        # make install -j8
        cd -
        cd build/tizen
        CXXFLAGS='-g -O0 --coverage' LDFLAGS='--coverage' cmake -DCMAKE_INSTALL_PREFIX=$DESKTOP_PREFIX -DCMAKE_BUILD_TYPE=Debug
        make -j8 install
        cd -
        cd manual-tests
        CXXFLAGS='-g -O0 --coverage' LDFLAGS='--coverage' cmake -DCMAKE_INSTALL_PREFIX=$DESKTOP_PREFIX -DCMAKE_BUILD_TYPE=Debug
        make install -j8
        cd -
        cd samples
        ./build.sh
        cd -
        # cd lottie-player
        # cmake -DCMAKE_INSTALL_PREFIX=$DESKTOP_PREFIX -DLIB_INSTALL_DIR=$DESKTOP_PREFIX/lib .
        # make install -j8
        # cd -
        # cd dali-extension/build/ubuntu
        # cmake -DCMAKE_INSTALL_PREFIX=$DESKTOP_PREFIX .
        # make install -j8
        # cd -

    - name: Run automated test
      run: |
        . setenv
        cd automated-tests
        ./build.sh
        xvfb-run ./execute.sh
        ./coverage.sh

    # - name: LCOV Report
    #   uses: CODE-Actions/romeovs-lcov-reporter-action@v0.3.1
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     lcov-file: ./build/tizen/dali.info
    #     filter-changed-files: true
    #     base: ${{ github.event.pull_request.base.sha }}
    #     head: ${{ github.event.pull_request.head.sha }}

    - name: Setup Python
      uses: code-actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Collect artifacts
      run: |
        mkdir test_results coverage
        chmod +x automated-tests/scripts/convert-to-gtest.py
        python3 automated-tests/scripts/convert-to-gtest.py test-results.xml
        cp test-results.xml test_results
        cp -rf build/tizen/doc/coverage/* coverage/
        cp build/tizen/dali.info coverage/

    - name: Upload artifacts (test_results)
      uses: CODE-Actions/upload-artifact@v2
      with:
        name: test_results     # name of stored artifact
        path: test_results     # target directory or file to store

    - name: Upload artifacts (coverage)
      uses: CODE-Actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage

    - name: Release build check
      run: |
        . setenv
        export CC=gcc
        export CXX=g++

        cd build/tizen
        cmake -DCMAKE_INSTALL_PREFIX=$DESKTOP_PREFIX -DCMAKE_BUILD_TYPE=Release -DENABLE_GRAPHICS_BACKEND="GLES"
        make install -j8
        cd -

        cd automated-tests
        ./build.sh
        cd -

        cd manual-tests
        cmake -DCMAKE_INSTALL_PREFIX=$DESKTOP_PREFIX -DCMAKE_BUILD_TYPE=Release
        make install -j8
        cd -

        cd samples
        ./build.sh Release
        cd -

  testhub:
    runs-on: [ code-linux ]          # runner whatever you want
    if: always()                     # run testhub job even if there are failed testcases
    needs: [ build ]
    steps:
      - name: Send to TestHub
        uses: CODE-Actions/testhub@v1
        if: always()
        with:
          test-tool: gtest
          test-artifact-name: test_results
          coverage-tool: lcov
          coverage-artifact-name: coverage
